/* This file was generated by SableCC (http://www.sablecc.org/). */

#include <sstream>

#include "node.h"
#include "token.h"
#include "lexer.h"

extern "C" {

static struct {
  const rose::_TypeInfo *type_info;
  const char *text;
} make_table[] = {
  {&rose::TDone::type_info, "done"},
  {&rose::TDraw::type_info, "draw"},
  {&rose::TElse::type_info, "else"},
  {&rose::TFace::type_info, "face"},
  {&rose::TFork::type_info, "fork"},
  {&rose::TMove::type_info, "move"},
  {&rose::TPlan::type_info, "plan"},
  {&rose::TProc::type_info, "proc"},
  {&rose::TRand::type_info, "rand"},
  {&rose::TSeed::type_info, "seed"},
  {&rose::TSine::type_info, "sine"},
  {&rose::TSize::type_info, "size"},
  {&rose::TTemp::type_info, "temp"},
  {&rose::TTint::type_info, "tint"},
  {&rose::TTurn::type_info, "turn"},
  {&rose::TWait::type_info, "wait"},
  {&rose::TWhen::type_info, "when"},
  {&rose::TLPar::type_info, "("},
  {&rose::TRPar::type_info, ")"},
  {&rose::TPlus::type_info, "+"},
  {&rose::TMinus::type_info, "-"},
  {&rose::TMul::type_info, "*"},
  {&rose::TDiv::type_info, "/"},
  {&rose::TEq::type_info, "--"},
  {&rose::TNe::type_info, "!="},
  {&rose::TLt::type_info, "<"},
  {&rose::TLe::type_info, "<="},
  {&rose::TGt::type_info, ">"},
  {&rose::TGe::type_info, ">="},
  {&rose::TAnd::type_info, "&"},
  {&rose::TOr::type_info, "|"},
  {&rose::TAssign::type_info, "="},
  {&rose::TNeg::type_info, "~"},
  {&rose::TNumber::type_info, ""},
  {&rose::TIdentifier::type_info, ""},
  {&rose::TColor::type_info, ""},
  {&rose::TBlank::type_info, ""},
  {&rose::TComment::type_info, ""},
};

static int _accept_1[] = { -1, 36, 36, 36, 36, -1, -1, 29, 17, 18, 21, 19, 20, 22, 33, 25, 31, 27, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 30, 32, 36, 24, -1, 37, 37, 23, -1, -1, 26, 28, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 37, 33, -1, -1, -1, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, -1, -1, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 35, 35, 35, };

static int *_accept[] = {
  _accept_1,
};

static int _g_1_1_1[] = {9, 9, 1};
static int _g_1_1_2[] = {10, 10, 2};
static int _g_1_1_3[] = {13, 13, 3};
static int _g_1_1_4[] = {32, 32, 4};
static int _g_1_1_5[] = {33, 33, 5};
static int _g_1_1_6[] = {35, 35, 6};
static int _g_1_1_7[] = {38, 38, 7};
static int _g_1_1_8[] = {40, 40, 8};
static int _g_1_1_9[] = {41, 41, 9};
static int _g_1_1_10[] = {42, 42, 10};
static int _g_1_1_11[] = {43, 43, 11};
static int _g_1_1_12[] = {45, 45, 12};
static int _g_1_1_13[] = {47, 47, 13};
static int _g_1_1_14[] = {48, 57, 14};
static int _g_1_1_15[] = {60, 60, 15};
static int _g_1_1_16[] = {61, 61, 16};
static int _g_1_1_17[] = {62, 62, 17};
static int _g_1_1_18[] = {65, 90, 18};
static int _g_1_1_19[] = {95, 95, 19};
static int _g_1_1_20[] = {97, 99, 20};
static int _g_1_1_21[] = {100, 100, 21};
static int _g_1_1_22[] = {101, 101, 22};
static int _g_1_1_23[] = {102, 102, 23};
static int _g_1_1_24[] = {103, 108, 20};
static int _g_1_1_25[] = {109, 109, 24};
static int _g_1_1_26[] = {110, 111, 20};
static int _g_1_1_27[] = {112, 112, 25};
static int _g_1_1_28[] = {113, 113, 20};
static int _g_1_1_29[] = {114, 114, 26};
static int _g_1_1_30[] = {115, 115, 27};
static int _g_1_1_31[] = {116, 116, 28};
static int _g_1_1_32[] = {117, 118, 20};
static int _g_1_1_33[] = {119, 119, 29};
static int _g_1_1_34[] = {120, 122, 20};
static int _g_1_1_35[] = {124, 124, 30};
static int _g_1_1_36[] = {126, 126, 31};
static int _g_1_2_1[] = {9, 32, -2};
static int _g_1_3_1[] = {9, 32, -2};
static int _g_1_4_1[] = {9, 9, 1};
static int _g_1_4_2[] = {10, 10, 32};
static int _g_1_4_3[] = {13, 32, -2};
static int _g_1_5_1[] = {9, 32, -2};
static int _g_1_6_1[] = {61, 61, 33};
static int _g_1_7_1[] = {0, 9, 34};
static int _g_1_7_2[] = {10, 10, 35};
static int _g_1_7_3[] = {11, 12, 34};
static int _g_1_7_4[] = {13, 13, 36};
static int _g_1_7_5[] = {14, 65535, 34};
static int _g_1_13_1[] = {45, 45, 37};
static int _g_1_15_1[] = {46, 46, 38};
static int _g_1_15_2[] = {48, 57, 14};
static int _g_1_15_3[] = {58, 58, 39};
static int _g_1_16_1[] = {61, 61, 40};
static int _g_1_18_1[] = {61, 61, 41};
static int _g_1_19_1[] = {48, 57, 42};
static int _g_1_19_2[] = {65, 90, 43};
static int _g_1_19_3[] = {95, 95, 44};
static int _g_1_19_4[] = {97, 122, 45};
static int _g_1_20_1[] = {48, 122, -20};
static int _g_1_21_1[] = {48, 122, -20};
static int _g_1_22_1[] = {48, 95, -20};
static int _g_1_22_2[] = {97, 110, 45};
static int _g_1_22_3[] = {111, 111, 46};
static int _g_1_22_4[] = {112, 113, 45};
static int _g_1_22_5[] = {114, 114, 47};
static int _g_1_22_6[] = {115, 122, 45};
static int _g_1_23_1[] = {48, 95, -20};
static int _g_1_23_2[] = {97, 107, 45};
static int _g_1_23_3[] = {108, 108, 48};
static int _g_1_23_4[] = {109, 122, 45};
static int _g_1_24_1[] = {48, 95, -20};
static int _g_1_24_2[] = {97, 97, 49};
static int _g_1_24_3[] = {98, 110, 45};
static int _g_1_24_4[] = {111, 111, 50};
static int _g_1_24_5[] = {112, 122, 45};
static int _g_1_25_1[] = {48, 110, -23};
static int _g_1_25_2[] = {111, 111, 51};
static int _g_1_25_3[] = {112, 122, 45};
static int _g_1_26_1[] = {48, 107, -24};
static int _g_1_26_2[] = {108, 108, 52};
static int _g_1_26_3[] = {109, 113, 45};
static int _g_1_26_4[] = {114, 114, 53};
static int _g_1_26_5[] = {115, 122, 45};
static int _g_1_27_1[] = {48, 95, -20};
static int _g_1_27_2[] = {97, 97, 54};
static int _g_1_27_3[] = {98, 122, 45};
static int _g_1_28_1[] = {48, 95, -20};
static int _g_1_28_2[] = {97, 100, 45};
static int _g_1_28_3[] = {101, 101, 55};
static int _g_1_28_4[] = {102, 104, 45};
static int _g_1_28_5[] = {105, 105, 56};
static int _g_1_28_6[] = {106, 122, 45};
static int _g_1_29_1[] = {48, 100, -29};
static int _g_1_29_2[] = {101, 101, 57};
static int _g_1_29_3[] = {102, 104, 45};
static int _g_1_29_4[] = {105, 105, 58};
static int _g_1_29_5[] = {106, 116, 45};
static int _g_1_29_6[] = {117, 117, 59};
static int _g_1_29_7[] = {118, 122, 45};
static int _g_1_30_1[] = {48, 95, -20};
static int _g_1_30_2[] = {97, 97, 60};
static int _g_1_30_3[] = {98, 103, 45};
static int _g_1_30_4[] = {104, 104, 61};
static int _g_1_30_5[] = {105, 122, 45};
static int _g_1_33_1[] = {9, 32, -2};
static int _g_1_35_1[] = {0, 65535, -8};
static int _g_1_37_1[] = {10, 10, 62};
static int _g_1_39_1[] = {48, 57, 63};
static int _g_1_40_1[] = {48, 57, 64};
static int _g_1_40_2[] = {65, 70, 65};
static int _g_1_40_3[] = {97, 102, 66};
static int _g_1_43_1[] = {48, 122, -20};
static int _g_1_44_1[] = {48, 122, -20};
static int _g_1_45_1[] = {48, 122, -20};
static int _g_1_46_1[] = {48, 122, -20};
static int _g_1_47_1[] = {48, 95, -20};
static int _g_1_47_2[] = {97, 109, 45};
static int _g_1_47_3[] = {110, 110, 67};
static int _g_1_47_4[] = {111, 122, 45};
static int _g_1_48_1[] = {48, 95, -20};
static int _g_1_48_2[] = {97, 97, 68};
static int _g_1_48_3[] = {98, 122, 45};
static int _g_1_49_1[] = {48, 95, -20};
static int _g_1_49_2[] = {97, 114, 45};
static int _g_1_49_3[] = {115, 115, 69};
static int _g_1_49_4[] = {116, 122, 45};
static int _g_1_50_1[] = {48, 95, -20};
static int _g_1_50_2[] = {97, 98, 45};
static int _g_1_50_3[] = {99, 99, 70};
static int _g_1_50_4[] = {100, 122, 45};
static int _g_1_51_1[] = {48, 95, -20};
static int _g_1_51_2[] = {97, 113, 45};
static int _g_1_51_3[] = {114, 114, 71};
static int _g_1_51_4[] = {115, 122, 45};
static int _g_1_52_1[] = {48, 95, -20};
static int _g_1_52_2[] = {97, 117, 45};
static int _g_1_52_3[] = {118, 118, 72};
static int _g_1_52_4[] = {119, 122, 45};
static int _g_1_53_1[] = {48, 95, -20};
static int _g_1_53_2[] = {97, 97, 73};
static int _g_1_53_3[] = {98, 122, 45};
static int _g_1_54_1[] = {48, 110, -23};
static int _g_1_54_2[] = {111, 111, 74};
static int _g_1_54_3[] = {112, 122, 45};
static int _g_1_55_1[] = {48, 109, -48};
static int _g_1_55_2[] = {110, 110, 75};
static int _g_1_55_3[] = {111, 122, 45};
static int _g_1_56_1[] = {48, 100, -29};
static int _g_1_56_2[] = {101, 101, 76};
static int _g_1_56_3[] = {102, 122, 45};
static int _g_1_57_1[] = {48, 109, -48};
static int _g_1_57_2[] = {110, 110, 77};
static int _g_1_57_3[] = {111, 121, 45};
static int _g_1_57_4[] = {122, 122, 78};
static int _g_1_58_1[] = {48, 95, -20};
static int _g_1_58_2[] = {97, 108, 45};
static int _g_1_58_3[] = {109, 109, 79};
static int _g_1_58_4[] = {110, 122, 45};
static int _g_1_59_1[] = {48, 109, -48};
static int _g_1_59_2[] = {110, 110, 80};
static int _g_1_59_3[] = {111, 122, 45};
static int _g_1_60_1[] = {48, 113, -52};
static int _g_1_60_2[] = {114, 114, 81};
static int _g_1_60_3[] = {115, 122, 45};
static int _g_1_61_1[] = {48, 95, -20};
static int _g_1_61_2[] = {97, 104, 45};
static int _g_1_61_3[] = {105, 105, 82};
static int _g_1_61_4[] = {106, 122, 45};
static int _g_1_62_1[] = {48, 100, -29};
static int _g_1_62_2[] = {101, 101, 83};
static int _g_1_62_3[] = {102, 122, 45};
static int _g_1_64_1[] = {48, 57, 63};
static int _g_1_65_1[] = {48, 57, 84};
static int _g_1_65_2[] = {65, 70, 85};
static int _g_1_65_3[] = {97, 102, 86};
static int _g_1_66_1[] = {48, 102, -66};
static int _g_1_67_1[] = {48, 102, -66};
static int _g_1_68_1[] = {48, 100, -29};
static int _g_1_68_2[] = {101, 101, 87};
static int _g_1_68_3[] = {102, 122, 45};
static int _g_1_69_1[] = {48, 95, -20};
static int _g_1_69_2[] = {97, 118, 45};
static int _g_1_69_3[] = {119, 119, 88};
static int _g_1_69_4[] = {120, 122, 45};
static int _g_1_70_1[] = {48, 100, -29};
static int _g_1_70_2[] = {101, 101, 89};
static int _g_1_70_3[] = {102, 122, 45};
static int _g_1_71_1[] = {48, 100, -29};
static int _g_1_71_2[] = {101, 101, 90};
static int _g_1_71_3[] = {102, 122, 45};
static int _g_1_72_1[] = {48, 95, -20};
static int _g_1_72_2[] = {97, 106, 45};
static int _g_1_72_3[] = {107, 107, 91};
static int _g_1_72_4[] = {108, 122, 45};
static int _g_1_73_1[] = {48, 100, -29};
static int _g_1_73_2[] = {101, 101, 92};
static int _g_1_73_3[] = {102, 122, 45};
static int _g_1_74_1[] = {48, 109, -48};
static int _g_1_74_2[] = {110, 110, 93};
static int _g_1_74_3[] = {111, 122, 45};
static int _g_1_75_1[] = {48, 98, -51};
static int _g_1_75_2[] = {99, 99, 94};
static int _g_1_75_3[] = {100, 122, 45};
static int _g_1_76_1[] = {48, 95, -20};
static int _g_1_76_2[] = {97, 99, 45};
static int _g_1_76_3[] = {100, 100, 95};
static int _g_1_76_4[] = {101, 122, 45};
static int _g_1_77_1[] = {48, 99, -77};
static int _g_1_77_2[] = {100, 100, 96};
static int _g_1_77_3[] = {101, 122, 45};
static int _g_1_78_1[] = {48, 100, -29};
static int _g_1_78_2[] = {101, 101, 97};
static int _g_1_78_3[] = {102, 122, 45};
static int _g_1_79_1[] = {48, 100, -29};
static int _g_1_79_2[] = {101, 101, 98};
static int _g_1_79_3[] = {102, 122, 45};
static int _g_1_80_1[] = {48, 95, -20};
static int _g_1_80_2[] = {97, 111, 45};
static int _g_1_80_3[] = {112, 112, 99};
static int _g_1_80_4[] = {113, 122, 45};
static int _g_1_81_1[] = {48, 95, -20};
static int _g_1_81_2[] = {97, 115, 45};
static int _g_1_81_3[] = {116, 116, 100};
static int _g_1_81_4[] = {117, 122, 45};
static int _g_1_82_1[] = {48, 109, -48};
static int _g_1_82_2[] = {110, 110, 101};
static int _g_1_82_3[] = {111, 122, 45};
static int _g_1_83_1[] = {48, 115, -82};
static int _g_1_83_2[] = {116, 116, 102};
static int _g_1_83_3[] = {117, 122, 45};
static int _g_1_84_1[] = {48, 109, -48};
static int _g_1_84_2[] = {110, 110, 103};
static int _g_1_84_3[] = {111, 122, 45};
static int _g_1_85_1[] = {48, 57, 104};
static int _g_1_85_2[] = {65, 70, 105};
static int _g_1_85_3[] = {97, 102, 106};
static int _g_1_86_1[] = {48, 102, -86};
static int _g_1_87_1[] = {48, 102, -86};
static int _g_1_88_1[] = {48, 122, -20};
static int _g_1_89_1[] = {48, 122, -20};
static int _g_1_90_1[] = {48, 122, -20};
static int _g_1_91_1[] = {48, 122, -20};
static int _g_1_92_1[] = {48, 122, -20};
static int _g_1_93_1[] = {48, 122, -20};
static int _g_1_94_1[] = {48, 122, -20};
static int _g_1_95_1[] = {48, 122, -20};
static int _g_1_96_1[] = {48, 122, -20};
static int _g_1_97_1[] = {48, 122, -20};
static int _g_1_98_1[] = {48, 122, -20};
static int _g_1_99_1[] = {48, 122, -20};
static int _g_1_100_1[] = {48, 122, -20};
static int _g_1_101_1[] = {48, 122, -20};
static int _g_1_102_1[] = {48, 122, -20};
static int _g_1_103_1[] = {48, 122, -20};
static int _g_1_104_1[] = {48, 122, -20};

static int *_g_1_1[] = {
        (int*)36,
        _g_1_1_1,
        _g_1_1_2,
        _g_1_1_3,
        _g_1_1_4,
        _g_1_1_5,
        _g_1_1_6,
        _g_1_1_7,
        _g_1_1_8,
        _g_1_1_9,
        _g_1_1_10,
        _g_1_1_11,
        _g_1_1_12,
        _g_1_1_13,
        _g_1_1_14,
        _g_1_1_15,
        _g_1_1_16,
        _g_1_1_17,
        _g_1_1_18,
        _g_1_1_19,
        _g_1_1_20,
        _g_1_1_21,
        _g_1_1_22,
        _g_1_1_23,
        _g_1_1_24,
        _g_1_1_25,
        _g_1_1_26,
        _g_1_1_27,
        _g_1_1_28,
        _g_1_1_29,
        _g_1_1_30,
        _g_1_1_31,
        _g_1_1_32,
        _g_1_1_33,
        _g_1_1_34,
        _g_1_1_35,
        _g_1_1_36,
};
static int *_g_1_2[] = {
        (int*)1,
        _g_1_2_1,
};
static int *_g_1_3[] = {
        (int*)1,
        _g_1_3_1,
};
static int *_g_1_4[] = {
        (int*)3,
        _g_1_4_1,
        _g_1_4_2,
        _g_1_4_3,
};
static int *_g_1_5[] = {
        (int*)1,
        _g_1_5_1,
};
static int *_g_1_6[] = {
        (int*)1,
        _g_1_6_1,
};
static int *_g_1_7[] = {
        (int*)5,
        _g_1_7_1,
        _g_1_7_2,
        _g_1_7_3,
        _g_1_7_4,
        _g_1_7_5,
};
static int *_g_1_8[] = {
        (int*)0,
};
static int *_g_1_9[] = {
        (int*)0,
};
static int *_g_1_10[] = {
        (int*)0,
};
static int *_g_1_11[] = {
        (int*)0,
};
static int *_g_1_12[] = {
        (int*)0,
};
static int *_g_1_13[] = {
        (int*)1,
        _g_1_13_1,
};
static int *_g_1_14[] = {
        (int*)0,
};
static int *_g_1_15[] = {
        (int*)3,
        _g_1_15_1,
        _g_1_15_2,
        _g_1_15_3,
};
static int *_g_1_16[] = {
        (int*)1,
        _g_1_16_1,
};
static int *_g_1_17[] = {
        (int*)0,
};
static int *_g_1_18[] = {
        (int*)1,
        _g_1_18_1,
};
static int *_g_1_19[] = {
        (int*)4,
        _g_1_19_1,
        _g_1_19_2,
        _g_1_19_3,
        _g_1_19_4,
};
static int *_g_1_20[] = {
        (int*)1,
        _g_1_20_1,
};
static int *_g_1_21[] = {
        (int*)1,
        _g_1_21_1,
};
static int *_g_1_22[] = {
        (int*)6,
        _g_1_22_1,
        _g_1_22_2,
        _g_1_22_3,
        _g_1_22_4,
        _g_1_22_5,
        _g_1_22_6,
};
static int *_g_1_23[] = {
        (int*)4,
        _g_1_23_1,
        _g_1_23_2,
        _g_1_23_3,
        _g_1_23_4,
};
static int *_g_1_24[] = {
        (int*)5,
        _g_1_24_1,
        _g_1_24_2,
        _g_1_24_3,
        _g_1_24_4,
        _g_1_24_5,
};
static int *_g_1_25[] = {
        (int*)3,
        _g_1_25_1,
        _g_1_25_2,
        _g_1_25_3,
};
static int *_g_1_26[] = {
        (int*)5,
        _g_1_26_1,
        _g_1_26_2,
        _g_1_26_3,
        _g_1_26_4,
        _g_1_26_5,
};
static int *_g_1_27[] = {
        (int*)3,
        _g_1_27_1,
        _g_1_27_2,
        _g_1_27_3,
};
static int *_g_1_28[] = {
        (int*)6,
        _g_1_28_1,
        _g_1_28_2,
        _g_1_28_3,
        _g_1_28_4,
        _g_1_28_5,
        _g_1_28_6,
};
static int *_g_1_29[] = {
        (int*)7,
        _g_1_29_1,
        _g_1_29_2,
        _g_1_29_3,
        _g_1_29_4,
        _g_1_29_5,
        _g_1_29_6,
        _g_1_29_7,
};
static int *_g_1_30[] = {
        (int*)5,
        _g_1_30_1,
        _g_1_30_2,
        _g_1_30_3,
        _g_1_30_4,
        _g_1_30_5,
};
static int *_g_1_31[] = {
        (int*)0,
};
static int *_g_1_32[] = {
        (int*)0,
};
static int *_g_1_33[] = {
        (int*)1,
        _g_1_33_1,
};
static int *_g_1_34[] = {
        (int*)0,
};
static int *_g_1_35[] = {
        (int*)1,
        _g_1_35_1,
};
static int *_g_1_36[] = {
        (int*)0,
};
static int *_g_1_37[] = {
        (int*)1,
        _g_1_37_1,
};
static int *_g_1_38[] = {
        (int*)0,
};
static int *_g_1_39[] = {
        (int*)1,
        _g_1_39_1,
};
static int *_g_1_40[] = {
        (int*)3,
        _g_1_40_1,
        _g_1_40_2,
        _g_1_40_3,
};
static int *_g_1_41[] = {
        (int*)0,
};
static int *_g_1_42[] = {
        (int*)0,
};
static int *_g_1_43[] = {
        (int*)1,
        _g_1_43_1,
};
static int *_g_1_44[] = {
        (int*)1,
        _g_1_44_1,
};
static int *_g_1_45[] = {
        (int*)1,
        _g_1_45_1,
};
static int *_g_1_46[] = {
        (int*)1,
        _g_1_46_1,
};
static int *_g_1_47[] = {
        (int*)4,
        _g_1_47_1,
        _g_1_47_2,
        _g_1_47_3,
        _g_1_47_4,
};
static int *_g_1_48[] = {
        (int*)3,
        _g_1_48_1,
        _g_1_48_2,
        _g_1_48_3,
};
static int *_g_1_49[] = {
        (int*)4,
        _g_1_49_1,
        _g_1_49_2,
        _g_1_49_3,
        _g_1_49_4,
};
static int *_g_1_50[] = {
        (int*)4,
        _g_1_50_1,
        _g_1_50_2,
        _g_1_50_3,
        _g_1_50_4,
};
static int *_g_1_51[] = {
        (int*)4,
        _g_1_51_1,
        _g_1_51_2,
        _g_1_51_3,
        _g_1_51_4,
};
static int *_g_1_52[] = {
        (int*)4,
        _g_1_52_1,
        _g_1_52_2,
        _g_1_52_3,
        _g_1_52_4,
};
static int *_g_1_53[] = {
        (int*)3,
        _g_1_53_1,
        _g_1_53_2,
        _g_1_53_3,
};
static int *_g_1_54[] = {
        (int*)3,
        _g_1_54_1,
        _g_1_54_2,
        _g_1_54_3,
};
static int *_g_1_55[] = {
        (int*)3,
        _g_1_55_1,
        _g_1_55_2,
        _g_1_55_3,
};
static int *_g_1_56[] = {
        (int*)3,
        _g_1_56_1,
        _g_1_56_2,
        _g_1_56_3,
};
static int *_g_1_57[] = {
        (int*)4,
        _g_1_57_1,
        _g_1_57_2,
        _g_1_57_3,
        _g_1_57_4,
};
static int *_g_1_58[] = {
        (int*)4,
        _g_1_58_1,
        _g_1_58_2,
        _g_1_58_3,
        _g_1_58_4,
};
static int *_g_1_59[] = {
        (int*)3,
        _g_1_59_1,
        _g_1_59_2,
        _g_1_59_3,
};
static int *_g_1_60[] = {
        (int*)3,
        _g_1_60_1,
        _g_1_60_2,
        _g_1_60_3,
};
static int *_g_1_61[] = {
        (int*)4,
        _g_1_61_1,
        _g_1_61_2,
        _g_1_61_3,
        _g_1_61_4,
};
static int *_g_1_62[] = {
        (int*)3,
        _g_1_62_1,
        _g_1_62_2,
        _g_1_62_3,
};
static int *_g_1_63[] = {
        (int*)0,
};
static int *_g_1_64[] = {
        (int*)1,
        _g_1_64_1,
};
static int *_g_1_65[] = {
        (int*)3,
        _g_1_65_1,
        _g_1_65_2,
        _g_1_65_3,
};
static int *_g_1_66[] = {
        (int*)1,
        _g_1_66_1,
};
static int *_g_1_67[] = {
        (int*)1,
        _g_1_67_1,
};
static int *_g_1_68[] = {
        (int*)3,
        _g_1_68_1,
        _g_1_68_2,
        _g_1_68_3,
};
static int *_g_1_69[] = {
        (int*)4,
        _g_1_69_1,
        _g_1_69_2,
        _g_1_69_3,
        _g_1_69_4,
};
static int *_g_1_70[] = {
        (int*)3,
        _g_1_70_1,
        _g_1_70_2,
        _g_1_70_3,
};
static int *_g_1_71[] = {
        (int*)3,
        _g_1_71_1,
        _g_1_71_2,
        _g_1_71_3,
};
static int *_g_1_72[] = {
        (int*)4,
        _g_1_72_1,
        _g_1_72_2,
        _g_1_72_3,
        _g_1_72_4,
};
static int *_g_1_73[] = {
        (int*)3,
        _g_1_73_1,
        _g_1_73_2,
        _g_1_73_3,
};
static int *_g_1_74[] = {
        (int*)3,
        _g_1_74_1,
        _g_1_74_2,
        _g_1_74_3,
};
static int *_g_1_75[] = {
        (int*)3,
        _g_1_75_1,
        _g_1_75_2,
        _g_1_75_3,
};
static int *_g_1_76[] = {
        (int*)4,
        _g_1_76_1,
        _g_1_76_2,
        _g_1_76_3,
        _g_1_76_4,
};
static int *_g_1_77[] = {
        (int*)3,
        _g_1_77_1,
        _g_1_77_2,
        _g_1_77_3,
};
static int *_g_1_78[] = {
        (int*)3,
        _g_1_78_1,
        _g_1_78_2,
        _g_1_78_3,
};
static int *_g_1_79[] = {
        (int*)3,
        _g_1_79_1,
        _g_1_79_2,
        _g_1_79_3,
};
static int *_g_1_80[] = {
        (int*)4,
        _g_1_80_1,
        _g_1_80_2,
        _g_1_80_3,
        _g_1_80_4,
};
static int *_g_1_81[] = {
        (int*)4,
        _g_1_81_1,
        _g_1_81_2,
        _g_1_81_3,
        _g_1_81_4,
};
static int *_g_1_82[] = {
        (int*)3,
        _g_1_82_1,
        _g_1_82_2,
        _g_1_82_3,
};
static int *_g_1_83[] = {
        (int*)3,
        _g_1_83_1,
        _g_1_83_2,
        _g_1_83_3,
};
static int *_g_1_84[] = {
        (int*)3,
        _g_1_84_1,
        _g_1_84_2,
        _g_1_84_3,
};
static int *_g_1_85[] = {
        (int*)3,
        _g_1_85_1,
        _g_1_85_2,
        _g_1_85_3,
};
static int *_g_1_86[] = {
        (int*)1,
        _g_1_86_1,
};
static int *_g_1_87[] = {
        (int*)1,
        _g_1_87_1,
};
static int *_g_1_88[] = {
        (int*)1,
        _g_1_88_1,
};
static int *_g_1_89[] = {
        (int*)1,
        _g_1_89_1,
};
static int *_g_1_90[] = {
        (int*)1,
        _g_1_90_1,
};
static int *_g_1_91[] = {
        (int*)1,
        _g_1_91_1,
};
static int *_g_1_92[] = {
        (int*)1,
        _g_1_92_1,
};
static int *_g_1_93[] = {
        (int*)1,
        _g_1_93_1,
};
static int *_g_1_94[] = {
        (int*)1,
        _g_1_94_1,
};
static int *_g_1_95[] = {
        (int*)1,
        _g_1_95_1,
};
static int *_g_1_96[] = {
        (int*)1,
        _g_1_96_1,
};
static int *_g_1_97[] = {
        (int*)1,
        _g_1_97_1,
};
static int *_g_1_98[] = {
        (int*)1,
        _g_1_98_1,
};
static int *_g_1_99[] = {
        (int*)1,
        _g_1_99_1,
};
static int *_g_1_100[] = {
        (int*)1,
        _g_1_100_1,
};
static int *_g_1_101[] = {
        (int*)1,
        _g_1_101_1,
};
static int *_g_1_102[] = {
        (int*)1,
        _g_1_102_1,
};
static int *_g_1_103[] = {
        (int*)1,
        _g_1_103_1,
};
static int *_g_1_104[] = {
        (int*)1,
        _g_1_104_1,
};
static int *_g_1_105[] = {
        (int*)0,
};
static int *_g_1_106[] = {
        (int*)0,
};
static int *_g_1_107[] = {
        (int*)0,
};

static int **_g_1[] = {
        _g_1_1,
        _g_1_2,
        _g_1_3,
        _g_1_4,
        _g_1_5,
        _g_1_6,
        _g_1_7,
        _g_1_8,
        _g_1_9,
        _g_1_10,
        _g_1_11,
        _g_1_12,
        _g_1_13,
        _g_1_14,
        _g_1_15,
        _g_1_16,
        _g_1_17,
        _g_1_18,
        _g_1_19,
        _g_1_20,
        _g_1_21,
        _g_1_22,
        _g_1_23,
        _g_1_24,
        _g_1_25,
        _g_1_26,
        _g_1_27,
        _g_1_28,
        _g_1_29,
        _g_1_30,
        _g_1_31,
        _g_1_32,
        _g_1_33,
        _g_1_34,
        _g_1_35,
        _g_1_36,
        _g_1_37,
        _g_1_38,
        _g_1_39,
        _g_1_40,
        _g_1_41,
        _g_1_42,
        _g_1_43,
        _g_1_44,
        _g_1_45,
        _g_1_46,
        _g_1_47,
        _g_1_48,
        _g_1_49,
        _g_1_50,
        _g_1_51,
        _g_1_52,
        _g_1_53,
        _g_1_54,
        _g_1_55,
        _g_1_56,
        _g_1_57,
        _g_1_58,
        _g_1_59,
        _g_1_60,
        _g_1_61,
        _g_1_62,
        _g_1_63,
        _g_1_64,
        _g_1_65,
        _g_1_66,
        _g_1_67,
        _g_1_68,
        _g_1_69,
        _g_1_70,
        _g_1_71,
        _g_1_72,
        _g_1_73,
        _g_1_74,
        _g_1_75,
        _g_1_76,
        _g_1_77,
        _g_1_78,
        _g_1_79,
        _g_1_80,
        _g_1_81,
        _g_1_82,
        _g_1_83,
        _g_1_84,
        _g_1_85,
        _g_1_86,
        _g_1_87,
        _g_1_88,
        _g_1_89,
        _g_1_90,
        _g_1_91,
        _g_1_92,
        _g_1_93,
        _g_1_94,
        _g_1_95,
        _g_1_96,
        _g_1_97,
        _g_1_98,
        _g_1_99,
        _g_1_100,
        _g_1_101,
        _g_1_102,
        _g_1_103,
        _g_1_104,
        _g_1_105,
        _g_1_106,
        _g_1_107,
};

static int ***_goto_table[] = {
        _g_1,
};

static rose::Lexer::State transitions[38][1] = {
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
          {
        rose::Lexer::INITIAL, 
},
};

} // extern "C" {


rose::StreamReader::StreamReader ( const std::string& path)
{
  std::filebuf *fbuf = new std::filebuf();
  fbuf->open (path.c_str(), std::ios::in|std::ios::binary);
  inbuf = fbuf;
  do_delete = true;
  eof = false;
}

rose::Lexer::Lexer (StreamReader *stream_reader, bool own_reader)
     : stream_reader (stream_reader), own_reader (own_reader)
{
  state = INITIAL;
  line = 0;
  pos = 0;
  cr = false;
}

rose::Lexer::Lexer (const std::string& path)
{
  stream_reader = new StreamReader (path);
  own_reader = true;
  state = INITIAL;
  line = 0;
  pos = 0;
  cr = false;
}

rose::Lexer::~Lexer ()
{
  if ( own_reader ) delete stream_reader;
}

rose::Token rose::Lexer::peek ()
{
  while ( !token ) {
      token = getToken ();
      filter();
  }

  return token;
}

rose::Token rose::Lexer::next ()
{
  while ( !token ) {
      token = getToken ();
      filter();
  }

  Token ret = token;
  token = Token();
  return ret;
}

void rose::Lexer::filter ()
{
}

void rose::Lexer::unread (Token token)
{
  const std::string& text = token.getText();
  for ( int i = (int) text.size() - 1; i >= 0; i-- )
      stream_reader->unget (text[i]);
  pos = token.getPos() - 1;
  line = token.getLine() - 1;
}

rose::Token rose::Lexer::getToken ()
{
  int dfa_state = 0;

  int start_pos = pos;
  int start_line = line;

  int accept_state = -1;
  int accept_token = -1;
  int accept_length = -1;
  int accept_pos = -1;
  int accept_line = -1;

  int ***goto_table = _goto_table[state];
  int *accept = _accept[state];
  text.clear();

  while (true) {
      int c = stream_reader->get();

      if ( c != -1 ) {
          switch (c) {
            case 10:
              if ( cr ) {
                  cr = false;
              } else {
                  line++;
                  pos = 0;
              }
              break;
            case 13:
              line++;
              pos = 0;
              cr = true;
              break;
            default:
              pos++;
              cr = false;
              break;

          }

          text.push_back(c);
          do {
              int oldState = (dfa_state < -1) ? (-2 - dfa_state) : dfa_state;

              dfa_state = -1;

              int** tmp1 =  goto_table[oldState];
              int low = 1;
              int high = (int) reinterpret_cast<size_t>(tmp1[0]);

              while(low <= high)
              {
                  int middle = (low + high) / 2;
                  int* tmp2 = tmp1[middle];

                  if(c < tmp2[0])
                  {
                      high = middle - 1;
                  }
                  else if(c > tmp2[1])
                  {
                      low = middle + 1;
                  }
                  else
                  {
                      dfa_state = tmp2[2];
                      break;
                  }
              }
          } while ( dfa_state < -1 );
      } else {
          dfa_state = -1;
      }

      if ( dfa_state >= 0 ) {
          if(accept[dfa_state] != -1) {
              accept_state = dfa_state;
              accept_token = accept[dfa_state];
              accept_length = (int) text.size();
              accept_pos = pos;
              accept_line = line;
          }
      } else {
          if ( accept_state != -1 ) {
              // pushBack
              for ( int i = (int)text.size() - 1; i >= accept_length; i-- )
                  stream_reader->unget (text[i]);

              pos = accept_pos;
              line = accept_line;

              int rline = start_line + 1;
              int rpos = start_pos + 1;

              state = transitions[accept_token][state];

              if ( make_table[accept_token].type_info->token_is_mutable ) {
                  return _GenericNode::initToken (make_table[accept_token].type_info,
                      rline, rpos, std::string (text.begin(), text.begin() + accept_length));
              } else {
                  return _GenericNode::initToken (make_table[accept_token].type_info,
                      rline, rpos, make_table[accept_token].text);
              }
          } else {
              if( text.size() ) {
                  std::ostringstream str;
                  str << "[" << (start_line + 1) << "," << (start_pos + 1) <<
                      "] Unknown token: " << std::string(text.begin(), text.end());
                  throw LexerException (start_line + 1, start_pos + 1, str.str());
              } else {
                  return TEOF::make(start_line + 1, start_pos + 1);
              }
          }
      }
  }
  throw Exception ("Should never get here");
}
