/* This file was generated by SableCC (http://www.sablecc.org/). */

#include <vector>
#include <string>
#include <stack>
#include <sstream>
#include <iostream>

#include "node.h"
#include "list.h"
#include "token.h"
#include "lexer.h"
#include "prod.h"
#include "parser.h"

using namespace rose;

extern "C" {

enum Command {
  CMD_POP,
  CMD_FETCHNODE,
  CMD_FETCHLIST,
  CMD_ADDNODE,
  CMD_ADDLIST,
  CMD_MAKELIST,
  CMD_MAKENODE,
  CMD_RETURNNODE,
  CMD_RETURNLIST
};

struct reduce_command {
  Command cmd;
  int result;
  int from;
  int index;
  int *args;
  const _TypeInfo *type_info;  // for makenode
};

static int rargs0[] = {0, 1};
static int rargs1[] = {0, 1};
static int rargs2[] = {0, 1};
static int rargs3[] = {0, 1};
static int rargs4[] = {0};
static int rargs5[] = {0};
static int rargs6[] = {0, 0, 1};
static int rargs7[] = {0, 0, 1};
static int rargs8[] = {0, 0, 1};
static int rargs9[] = {0, 0, 1};
static int rargs10[] = {0};
static int rargs11[] = {0};
static int rargs12[] = {0};
static int rargs13[] = {0, 1};
static int rargs14[] = {0, 1};
static int rargs15[] = {0, 1};
static int rargs16[] = {0, 1};
static int rargs17[] = {0, 1};
static int rargs18[] = {0, 1};
static int rargs19[] = {1};
static int rargs20[] = {0, 2, 0};
static int rargs21[] = {1};
static int rargs22[] = {0, 2, 0};
static int rargs23[] = {0};
static int rargs24[] = {1, 2};
static int rargs25[] = {0, 1};
static int rargs26[] = {};
static int rargs27[] = {0, 1, 0, 2, 1};
static int rargs28[] = {};
static int rargs29[] = {0, 1, 0, 2, 1};
static int rargs30[] = {};
static int rargs31[] = {0, 1, 0, 2, 1};
static int rargs32[] = {};
static int rargs33[] = {0, 1, 0, 2, 1};
static int rargs34[] = {};
static int rargs35[] = {0, 1, 0, 2, 1};
static int rargs36[] = {};
static int rargs37[] = {0, 1, 0, 2, 1};
static int rargs38[] = {0, 1, 2, 3};
static int rargs39[] = {0};
static int rargs40[] = {1, 2, 3};
static int rargs41[] = {0};
static int rargs42[] = {1, 2, 3};
static int rargs43[] = {0};
static int rargs44[] = {1, 2, 3};
static int rargs45[] = {0};
static int rargs46[] = {1, 2, 3};
static int rargs47[] = {0};
static int rargs48[] = {1, 2, 3};
static int rargs49[] = {0};
static int rargs50[] = {1, 2, 3};
static int rargs51[] = {0};
static int rargs52[] = {1, 2, 3};
static int rargs53[] = {0};
static int rargs54[] = {1, 2, 3};
static int rargs55[] = {0};
static int rargs56[] = {1, 2, 3};
static int rargs57[] = {0};
static int rargs58[] = {1, 2, 3};
static int rargs59[] = {0};
static int rargs60[] = {1, 2, 3};
static int rargs61[] = {0};
static int rargs62[] = {1, 2, 3};
static int rargs63[] = {0, 1};
static int rargs64[] = {0};
static int rargs65[] = {0};
static int rargs66[] = {0, 1};
static int rargs67[] = {0};

static reduce_command rcmd0[] = {
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_MAKENODE, 0, -1, -1, rargs0, &AProgram::type_info}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd1[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHLIST, 2, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 2, -1, 0, 0}, 
  {CMD_MAKENODE, 0, -1, -1, rargs1, &AProgram::type_info}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd2[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHLIST, 2, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 1, 2, -1, 0, 0}, 
  {CMD_MAKENODE, 0, -1, -1, rargs2, &AProgram::type_info}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd3[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHLIST, 2, 1, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 2, -1, 0, 0}, 
  {CMD_FETCHLIST, 3, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 1, 3, -1, 0, 0}, 
  {CMD_MAKENODE, 0, -1, -1, rargs3, &AProgram::type_info}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd4[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd5[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHLIST, 1, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 1, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd6[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs4, &AWaitEvent::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd7[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs5, &AColorEvent::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd8[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs6, &AProcedure::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd9[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHLIST, 2, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 2, -1, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs7, &AProcedure::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd10[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHLIST, 2, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 1, 2, -1, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs8, &AProcedure::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd11[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_POP, 3, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 2, 0, 0, 0}, 
  {CMD_FETCHLIST, 2, 1, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 2, -1, 0, 0}, 
  {CMD_FETCHLIST, 3, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 1, 3, -1, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs9, &AProcedure::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd12[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs10, &ALocal::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd13[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs11, &ADefyStatement::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd14[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs12, &ADrawStatement::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd15[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs13, &AMoveStatement::type_info}, 
  {CMD_RETURNNODE, -1, 2, -1, 0, 0}
};
static reduce_command rcmd16[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs14, &ATurnStatement::type_info}, 
  {CMD_RETURNNODE, -1, 2, -1, 0, 0}
};
static reduce_command rcmd17[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs15, &AFaceStatement::type_info}, 
  {CMD_RETURNNODE, -1, 2, -1, 0, 0}
};
static reduce_command rcmd18[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs16, &ATintStatement::type_info}, 
  {CMD_RETURNNODE, -1, 2, -1, 0, 0}
};
static reduce_command rcmd19[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs17, &ASizeStatement::type_info}, 
  {CMD_RETURNNODE, -1, 2, -1, 0, 0}
};
static reduce_command rcmd20[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs18, &AWaitStatement::type_info}, 
  {CMD_RETURNNODE, -1, 2, -1, 0, 0}
};
static reduce_command rcmd21[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs19, &AVarExpression::type_info}, 
  {CMD_MAKENODE, 3, -1, -1, rargs20, &AForkStatement::type_info}, 
  {CMD_RETURNNODE, -1, 3, -1, 0, 0}
};
static reduce_command rcmd22[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs21, &AVarExpression::type_info}, 
  {CMD_FETCHLIST, 1, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 1, -1, 0, 0}, 
  {CMD_MAKENODE, 3, -1, -1, rargs22, &AForkStatement::type_info}, 
  {CMD_RETURNNODE, -1, 3, -1, 0, 0}
};
static reduce_command rcmd23[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_POP, 3, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 2, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs23, &ALocal::type_info}, 
  {CMD_FETCHNODE, 2, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 3, -1, -1, rargs24, &ATempStatement::type_info}, 
  {CMD_RETURNNODE, -1, 3, -1, 0, 0}
};
static reduce_command rcmd24[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs25, &ASeedStatement::type_info}, 
  {CMD_RETURNNODE, -1, 2, -1, 0, 0}
};
static reduce_command rcmd25[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs26, &AElseMarker::type_info}, 
  {CMD_MAKENODE, 3, -1, -1, rargs27, &AWhenStatement::type_info}, 
  {CMD_RETURNNODE, -1, 3, -1, 0, 0}
};
static reduce_command rcmd26[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_POP, 3, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 3, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 2, 0, 0, 0}, 
  {CMD_FETCHLIST, 2, 1, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 2, -1, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs28, &AElseMarker::type_info}, 
  {CMD_MAKENODE, 3, -1, -1, rargs29, &AWhenStatement::type_info}, 
  {CMD_RETURNNODE, -1, 3, -1, 0, 0}
};
static reduce_command rcmd27[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_POP, 3, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 3, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 2, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs30, &AElseMarker::type_info}, 
  {CMD_MAKENODE, 3, -1, -1, rargs31, &AWhenStatement::type_info}, 
  {CMD_RETURNNODE, -1, 3, -1, 0, 0}
};
static reduce_command rcmd28[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_POP, 3, -1, -1, 0, 0}, 
  {CMD_POP, 4, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 4, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 3, 0, 0, 0}, 
  {CMD_FETCHLIST, 2, 2, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 2, -1, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs32, &AElseMarker::type_info}, 
  {CMD_MAKENODE, 3, -1, -1, rargs33, &AWhenStatement::type_info}, 
  {CMD_RETURNNODE, -1, 3, -1, 0, 0}
};
static reduce_command rcmd29[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_POP, 3, -1, -1, 0, 0}, 
  {CMD_POP, 4, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 4, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 3, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs34, &AElseMarker::type_info}, 
  {CMD_FETCHLIST, 2, 1, 0, 0, 0}, 
  {CMD_ADDLIST, 1, 2, -1, 0, 0}, 
  {CMD_MAKENODE, 3, -1, -1, rargs35, &AWhenStatement::type_info}, 
  {CMD_RETURNNODE, -1, 3, -1, 0, 0}
};
static reduce_command rcmd30[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_POP, 3, -1, -1, 0, 0}, 
  {CMD_POP, 4, -1, -1, 0, 0}, 
  {CMD_POP, 5, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 5, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 4, 0, 0, 0}, 
  {CMD_FETCHLIST, 2, 3, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 2, -1, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs36, &AElseMarker::type_info}, 
  {CMD_FETCHLIST, 3, 1, 0, 0, 0}, 
  {CMD_ADDLIST, 1, 3, -1, 0, 0}, 
  {CMD_MAKENODE, 3, -1, -1, rargs37, &AWhenStatement::type_info}, 
  {CMD_RETURNNODE, -1, 3, -1, 0, 0}
};
static reduce_command rcmd31[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd32[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_POP, 3, -1, -1, 0, 0}, 
  {CMD_POP, 4, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 3, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 4, 0, 0, 0}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs38, &ACondExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd33[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd34[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs39, &AOrBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs40, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd35[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd36[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs41, &AAndBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs42, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd37[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd38[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs43, &AEqBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs44, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd39[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs45, &ANeBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs46, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd40[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs47, &ALtBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs48, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd41[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs49, &ALeBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs50, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd42[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs51, &AGtBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs52, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd43[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs53, &AGeBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs54, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd44[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd45[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs55, &APlusBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs56, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd46[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs57, &AMinusBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs58, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd47[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd48[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs59, &AMultiplyBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs60, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd49[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs61, &ADivideBinop::type_info}, 
  {CMD_FETCHNODE, 2, 2, 0, 0, 0}, 
  {CMD_FETCHNODE, 3, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 4, -1, -1, rargs62, &ABinaryExpression::type_info}, 
  {CMD_RETURNNODE, -1, 4, -1, 0, 0}
};
static reduce_command rcmd50[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs63, &ANegExpression::type_info}, 
  {CMD_RETURNNODE, -1, 2, -1, 0, 0}
};
static reduce_command rcmd51[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs64, &AVarExpression::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd52[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs65, &ANumberExpression::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd53[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 1, 0, 0, 0}, 
  {CMD_RETURNNODE, -1, 0, -1, 0, 0}
};
static reduce_command rcmd54[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_POP, 2, -1, -1, 0, 0}, 
  {CMD_POP, 3, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 3, 0, 0, 0}, 
  {CMD_FETCHNODE, 1, 1, 0, 0, 0}, 
  {CMD_MAKENODE, 2, -1, -1, rargs66, &ASineExpression::type_info}, 
  {CMD_RETURNNODE, -1, 2, -1, 0, 0}
};
static reduce_command rcmd55[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_MAKENODE, 1, -1, -1, rargs67, &ARandExpression::type_info}, 
  {CMD_RETURNNODE, -1, 1, -1, 0, 0}
};
static reduce_command rcmd56[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd57[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHLIST, 1, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 1, -1, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd58[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd59[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHLIST, 1, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 1, -1, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd60[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd61[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHLIST, 1, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 1, -1, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd62[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd63[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHLIST, 1, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 1, -1, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd64[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};
static reduce_command rcmd65[] = {
  {CMD_POP, 0, -1, -1, 0, 0}, 
  {CMD_POP, 1, -1, -1, 0, 0}, 
  {CMD_MAKELIST, 0, -1, -1, 0, 0}, 
  {CMD_FETCHLIST, 1, 1, 0, 0, 0}, 
  {CMD_FETCHNODE, 0, 0, 0, 0, 0}, 
  {CMD_ADDLIST, 0, 1, -1, 0, 0}, 
  {CMD_ADDNODE, 0, 0, -1, 0, 0}, 
  {CMD_RETURNLIST, -1, 0, -1, 0, 0}
};

static struct {
  int count;
  int go_to;
  reduce_command *commands;
} reduce_commands[] = {
  {4, 0, rcmd0},
  {7, 0, rcmd1},
  {7, 0, rcmd2},
  {10, 0, rcmd3},
  {3, 1, rcmd4},
  {6, 1, rcmd5},
  {5, 2, rcmd6},
  {4, 2, rcmd7},
  {7, 3, rcmd8},
  {10, 3, rcmd9},
  {10, 3, rcmd10},
  {13, 3, rcmd11},
  {4, 4, rcmd12},
  {4, 5, rcmd13},
  {4, 5, rcmd14},
  {6, 5, rcmd15},
  {6, 5, rcmd16},
  {6, 5, rcmd17},
  {6, 5, rcmd18},
  {6, 5, rcmd19},
  {6, 5, rcmd20},
  {8, 5, rcmd21},
  {11, 5, rcmd22},
  {9, 5, rcmd23},
  {6, 5, rcmd24},
  {10, 5, rcmd25},
  {13, 5, rcmd26},
  {11, 5, rcmd27},
  {14, 5, rcmd28},
  {14, 5, rcmd29},
  {17, 5, rcmd30},
  {3, 6, rcmd31},
  {11, 6, rcmd32},
  {3, 7, rcmd33},
  {9, 7, rcmd34},
  {3, 8, rcmd35},
  {9, 8, rcmd36},
  {3, 9, rcmd37},
  {9, 9, rcmd38},
  {9, 9, rcmd39},
  {9, 9, rcmd40},
  {9, 9, rcmd41},
  {9, 9, rcmd42},
  {9, 9, rcmd43},
  {3, 10, rcmd44},
  {9, 10, rcmd45},
  {9, 10, rcmd46},
  {3, 11, rcmd47},
  {9, 11, rcmd48},
  {9, 11, rcmd49},
  {6, 12, rcmd50},
  {4, 12, rcmd51},
  {4, 12, rcmd52},
  {5, 12, rcmd53},
  {8, 12, rcmd54},
  {4, 12, rcmd55},
  {5, 13, rcmd56},
  {8, 13, rcmd57},
  {5, 14, rcmd58},
  {8, 14, rcmd59},
  {5, 15, rcmd60},
  {8, 15, rcmd61},
  {5, 16, rcmd62},
  {8, 16, rcmd63},
  {5, 17, rcmd64},
  {8, 17, rcmd65},
};

static int _g_1_1[] = {-1, 3};
static int _g_2_1[] = {-1, 4};
static int _g_3_1[] = {-1, 9};
static int _g_3_2[] = {10, 27};
static int _g_4_1[] = {-1, 5};
static int _g_4_2[] = {6, 13};
static int _g_4_3[] = {12, 13};
static int _g_5_1[] = {-1, 41};
static int _g_5_2[] = {43, 71};
static int _g_6_1[] = {-1, 42};
static int _g_6_2[] = {44, 73};
static int _g_6_3[] = {72, 73};
static int _g_6_4[] = {94, 73};
static int _g_6_5[] = {100, 73};
static int _g_6_6[] = {106, 73};
static int _g_7_1[] = {-1, 20};
static int _g_7_2[] = {16, 46};
static int _g_7_3[] = {30, 61};
static int _g_7_4[] = {32, 63};
static int _g_7_5[] = {33, 64};
static int _g_7_6[] = {34, 65};
static int _g_7_7[] = {36, 67};
static int _g_7_8[] = {37, 68};
static int _g_7_9[] = {38, 69};
static int _g_7_10[] = {39, 70};
static int _g_7_11[] = {45, 74};
static int _g_7_12[] = {49, 77};
static int _g_7_13[] = {62, 89};
static int _g_7_14[] = {90, 97};
static int _g_7_15[] = {91, 98};
static int _g_7_16[] = {96, 103};
static int _g_8_1[] = {-1, 21};
static int _g_9_1[] = {-1, 22};
static int _g_9_2[] = {48, 76};
static int _g_10_1[] = {-1, 23};
static int _g_10_2[] = {50, 78};
static int _g_11_1[] = {-1, 24};
static int _g_11_2[] = {53, 81};
static int _g_11_3[] = {54, 82};
static int _g_11_4[] = {55, 83};
static int _g_11_5[] = {56, 84};
static int _g_11_6[] = {57, 85};
static int _g_11_7[] = {58, 86};
static int _g_12_1[] = {-1, 25};
static int _g_12_2[] = {51, 79};
static int _g_12_3[] = {52, 80};
static int _g_13_1[] = {-1, 26};
static int _g_13_2[] = {17, 47};
static int _g_13_3[] = {59, 87};
static int _g_13_4[] = {60, 88};
static int _g_14_1[] = {-1, 6};
static int _g_14_2[] = {4, 12};
static int _g_15_1[] = {-1, 10};
static int _g_16_1[] = {-1, 43};
static int _g_17_1[] = {-1, 44};
static int _g_17_2[] = {43, 72};
static int _g_17_3[] = {70, 94};
static int _g_17_4[] = {93, 100};
static int _g_17_5[] = {102, 106};
static int _g_18_1[] = {-1, 90};

static int *_g_1[] = {
        (int *)1,
        _g_1_1,
};
static int *_g_2[] = {
        (int *)1,
        _g_2_1,
};
static int *_g_3[] = {
        (int *)2,
        _g_3_1,
        _g_3_2,
};
static int *_g_4[] = {
        (int *)3,
        _g_4_1,
        _g_4_2,
        _g_4_3,
};
static int *_g_5[] = {
        (int *)2,
        _g_5_1,
        _g_5_2,
};
static int *_g_6[] = {
        (int *)6,
        _g_6_1,
        _g_6_2,
        _g_6_3,
        _g_6_4,
        _g_6_5,
        _g_6_6,
};
static int *_g_7[] = {
        (int *)16,
        _g_7_1,
        _g_7_2,
        _g_7_3,
        _g_7_4,
        _g_7_5,
        _g_7_6,
        _g_7_7,
        _g_7_8,
        _g_7_9,
        _g_7_10,
        _g_7_11,
        _g_7_12,
        _g_7_13,
        _g_7_14,
        _g_7_15,
        _g_7_16,
};
static int *_g_8[] = {
        (int *)1,
        _g_8_1,
};
static int *_g_9[] = {
        (int *)2,
        _g_9_1,
        _g_9_2,
};
static int *_g_10[] = {
        (int *)2,
        _g_10_1,
        _g_10_2,
};
static int *_g_11[] = {
        (int *)7,
        _g_11_1,
        _g_11_2,
        _g_11_3,
        _g_11_4,
        _g_11_5,
        _g_11_6,
        _g_11_7,
};
static int *_g_12[] = {
        (int *)3,
        _g_12_1,
        _g_12_2,
        _g_12_3,
};
static int *_g_13[] = {
        (int *)4,
        _g_13_1,
        _g_13_2,
        _g_13_3,
        _g_13_4,
};
static int *_g_14[] = {
        (int *)2,
        _g_14_1,
        _g_14_2,
};
static int *_g_15[] = {
        (int *)1,
        _g_15_1,
};
static int *_g_16[] = {
        (int *)1,
        _g_16_1,
};
static int *_g_17[] = {
        (int *)5,
        _g_17_1,
        _g_17_2,
        _g_17_3,
        _g_17_4,
        _g_17_5,
};
static int *_g_18[] = {
        (int *)1,
        _g_18_1,
};

static int **goto_table[] = {
        _g_1,
        _g_2,
        _g_3,
        _g_4,
        _g_5,
        _g_6,
        _g_7,
        _g_8,
        _g_9,
        _g_10,
        _g_11,
        _g_12,
        _g_13,
        _g_14,
        _g_15,
        _g_16,
        _g_17,
        _g_18,
};

static int _a_1_1[] = {-1, 1, 0};
static int _a_1_2[] = {7, 0, 1};
static int _a_1_3[] = {8, 0, 2};
static int _a_2_1[] = {-1, 1, 4};
static int _a_2_2[] = {16, 0, 7};
static int _a_2_3[] = {38, 0, 8};
static int _a_3_1[] = {-1, 3, 2};
static int _a_3_2[] = {37, 0, 11};
static int _a_4_1[] = {-1, 3, 3};
static int _a_4_2[] = {39, 2, -1};
static int _a_5_1[] = {-1, 1, 1};
static int _a_5_2[] = {8, 0, 2};
static int _a_6_1[] = {-1, 1, 56};
static int _a_7_1[] = {-1, 1, 2};
static int _a_7_2[] = {8, 0, 2};
static int _a_8_1[] = {-1, 3, 7};
static int _a_8_2[] = {9, 0, 14};
static int _a_8_3[] = {11, 0, 15};
static int _a_8_4[] = {18, 0, 16};
static int _a_8_5[] = {33, 0, 17};
static int _a_8_6[] = {36, 0, 18};
static int _a_8_7[] = {37, 0, 19};
static int _a_9_1[] = {-1, 1, 7};
static int _a_10_1[] = {-1, 1, 58};
static int _a_11_1[] = {-1, 1, 5};
static int _a_11_2[] = {16, 0, 7};
static int _a_11_3[] = {38, 0, 8};
static int _a_12_1[] = {-1, 1, 8};
static int _a_12_2[] = {0, 0, 28};
static int _a_12_3[] = {2, 0, 29};
static int _a_12_4[] = {4, 0, 30};
static int _a_12_5[] = {5, 0, 31};
static int _a_12_6[] = {6, 0, 32};
static int _a_12_7[] = {10, 0, 33};
static int _a_12_8[] = {12, 0, 34};
static int _a_12_9[] = {13, 0, 35};
static int _a_12_10[] = {14, 0, 36};
static int _a_12_11[] = {15, 0, 37};
static int _a_12_12[] = {16, 0, 38};
static int _a_12_13[] = {17, 0, 39};
static int _a_12_14[] = {37, 0, 40};
static int _a_13_1[] = {-1, 1, 3};
static int _a_13_2[] = {8, 0, 2};
static int _a_14_1[] = {-1, 1, 57};
static int _a_15_1[] = {-1, 1, 55};
static int _a_16_1[] = {-1, 3, 15};
static int _a_16_2[] = {18, 0, 45};
static int _a_17_1[] = {-1, 3, 16};
static int _a_17_2[] = {9, 0, 14};
static int _a_17_3[] = {11, 0, 15};
static int _a_17_4[] = {18, 0, 16};
static int _a_17_5[] = {33, 0, 17};
static int _a_17_6[] = {36, 0, 18};
static int _a_17_7[] = {37, 0, 19};
static int _a_18_1[] = {-1, 3, 17};
static int _a_18_2[] = {9, 0, 14};
static int _a_18_3[] = {11, 0, 15};
static int _a_18_4[] = {18, 0, 16};
static int _a_18_5[] = {33, 0, 17};
static int _a_18_6[] = {36, 0, 18};
static int _a_18_7[] = {37, 0, 19};
static int _a_19_1[] = {-1, 1, 52};
static int _a_20_1[] = {-1, 1, 51};
static int _a_21_1[] = {-1, 1, 6};
static int _a_22_1[] = {-1, 1, 31};
static int _a_22_2[] = {31, 0, 48};
static int _a_22_3[] = {34, 0, 49};
static int _a_23_1[] = {-1, 1, 33};
static int _a_23_2[] = {30, 0, 50};
static int _a_24_1[] = {-1, 1, 35};
static int _a_25_1[] = {-1, 1, 37};
static int _a_25_2[] = {20, 0, 51};
static int _a_25_3[] = {21, 0, 52};
static int _a_25_4[] = {24, 0, 53};
static int _a_25_5[] = {25, 0, 54};
static int _a_25_6[] = {26, 0, 55};
static int _a_25_7[] = {27, 0, 56};
static int _a_25_8[] = {28, 0, 57};
static int _a_25_9[] = {29, 0, 58};
static int _a_26_1[] = {-1, 1, 44};
static int _a_26_2[] = {22, 0, 59};
static int _a_26_3[] = {23, 0, 60};
static int _a_27_1[] = {-1, 1, 47};
static int _a_28_1[] = {-1, 1, 59};
static int _a_29_1[] = {-1, 1, 13};
static int _a_30_1[] = {-1, 1, 14};
static int _a_31_1[] = {-1, 3, 30};
static int _a_31_2[] = {9, 0, 14};
static int _a_31_3[] = {11, 0, 15};
static int _a_31_4[] = {18, 0, 16};
static int _a_31_5[] = {33, 0, 17};
static int _a_31_6[] = {36, 0, 18};
static int _a_31_7[] = {37, 0, 19};
static int _a_32_1[] = {-1, 3, 31};
static int _a_32_2[] = {37, 0, 62};
static int _a_33_1[] = {-1, 3, 32};
static int _a_33_2[] = {9, 0, 14};
static int _a_33_3[] = {11, 0, 15};
static int _a_33_4[] = {18, 0, 16};
static int _a_33_5[] = {33, 0, 17};
static int _a_33_6[] = {36, 0, 18};
static int _a_33_7[] = {37, 0, 19};
static int _a_34_1[] = {-1, 3, 33};
static int _a_34_2[] = {9, 0, 14};
static int _a_34_3[] = {11, 0, 15};
static int _a_34_4[] = {18, 0, 16};
static int _a_34_5[] = {33, 0, 17};
static int _a_34_6[] = {36, 0, 18};
static int _a_34_7[] = {37, 0, 19};
static int _a_35_1[] = {-1, 3, 34};
static int _a_35_2[] = {9, 0, 14};
static int _a_35_3[] = {11, 0, 15};
static int _a_35_4[] = {18, 0, 16};
static int _a_35_5[] = {33, 0, 17};
static int _a_35_6[] = {36, 0, 18};
static int _a_35_7[] = {37, 0, 19};
static int _a_36_1[] = {-1, 3, 35};
static int _a_36_2[] = {37, 0, 66};
static int _a_37_1[] = {-1, 3, 36};
static int _a_37_2[] = {9, 0, 14};
static int _a_37_3[] = {11, 0, 15};
static int _a_37_4[] = {18, 0, 16};
static int _a_37_5[] = {33, 0, 17};
static int _a_37_6[] = {36, 0, 18};
static int _a_37_7[] = {37, 0, 19};
static int _a_38_1[] = {-1, 3, 37};
static int _a_38_2[] = {9, 0, 14};
static int _a_38_3[] = {11, 0, 15};
static int _a_38_4[] = {18, 0, 16};
static int _a_38_5[] = {33, 0, 17};
static int _a_38_6[] = {36, 0, 18};
static int _a_38_7[] = {37, 0, 19};
static int _a_39_1[] = {-1, 3, 38};
static int _a_39_2[] = {9, 0, 14};
static int _a_39_3[] = {11, 0, 15};
static int _a_39_4[] = {18, 0, 16};
static int _a_39_5[] = {33, 0, 17};
static int _a_39_6[] = {36, 0, 18};
static int _a_39_7[] = {37, 0, 19};
static int _a_40_1[] = {-1, 3, 39};
static int _a_40_2[] = {9, 0, 14};
static int _a_40_3[] = {11, 0, 15};
static int _a_40_4[] = {18, 0, 16};
static int _a_40_5[] = {33, 0, 17};
static int _a_40_6[] = {36, 0, 18};
static int _a_40_7[] = {37, 0, 19};
static int _a_41_1[] = {-1, 1, 12};
static int _a_42_1[] = {-1, 1, 60};
static int _a_43_1[] = {-1, 1, 62};
static int _a_44_1[] = {-1, 1, 9};
static int _a_44_2[] = {0, 0, 28};
static int _a_44_3[] = {2, 0, 29};
static int _a_44_4[] = {4, 0, 30};
static int _a_44_5[] = {5, 0, 31};
static int _a_44_6[] = {6, 0, 32};
static int _a_44_7[] = {10, 0, 33};
static int _a_44_8[] = {12, 0, 34};
static int _a_44_9[] = {13, 0, 35};
static int _a_44_10[] = {14, 0, 36};
static int _a_44_11[] = {15, 0, 37};
static int _a_44_12[] = {16, 0, 38};
static int _a_44_13[] = {17, 0, 39};
static int _a_44_14[] = {37, 0, 40};
static int _a_45_1[] = {-1, 1, 10};
static int _a_45_2[] = {0, 0, 28};
static int _a_45_3[] = {2, 0, 29};
static int _a_45_4[] = {4, 0, 30};
static int _a_45_5[] = {5, 0, 31};
static int _a_45_6[] = {6, 0, 32};
static int _a_45_7[] = {10, 0, 33};
static int _a_45_8[] = {12, 0, 34};
static int _a_45_9[] = {13, 0, 35};
static int _a_45_10[] = {14, 0, 36};
static int _a_45_11[] = {15, 0, 37};
static int _a_45_12[] = {16, 0, 38};
static int _a_45_13[] = {17, 0, 39};
static int _a_46_1[] = {-1, 3, 45};
static int _a_46_2[] = {9, 0, 14};
static int _a_46_3[] = {11, 0, 15};
static int _a_46_4[] = {18, 0, 16};
static int _a_46_5[] = {33, 0, 17};
static int _a_46_6[] = {36, 0, 18};
static int _a_46_7[] = {37, 0, 19};
static int _a_47_1[] = {-1, 3, 46};
static int _a_47_2[] = {19, 0, 75};
static int _a_48_1[] = {-1, 1, 50};
static int _a_49_1[] = {-1, 3, 48};
static int _a_49_2[] = {9, 0, 14};
static int _a_49_3[] = {11, 0, 15};
static int _a_49_4[] = {18, 0, 16};
static int _a_49_5[] = {33, 0, 17};
static int _a_49_6[] = {36, 0, 18};
static int _a_49_7[] = {37, 0, 19};
static int _a_50_1[] = {-1, 3, 49};
static int _a_50_2[] = {9, 0, 14};
static int _a_50_3[] = {11, 0, 15};
static int _a_50_4[] = {18, 0, 16};
static int _a_50_5[] = {33, 0, 17};
static int _a_50_6[] = {36, 0, 18};
static int _a_50_7[] = {37, 0, 19};
static int _a_51_1[] = {-1, 3, 50};
static int _a_51_2[] = {9, 0, 14};
static int _a_51_3[] = {11, 0, 15};
static int _a_51_4[] = {18, 0, 16};
static int _a_51_5[] = {33, 0, 17};
static int _a_51_6[] = {36, 0, 18};
static int _a_51_7[] = {37, 0, 19};
static int _a_52_1[] = {-1, 3, 51};
static int _a_52_2[] = {9, 0, 14};
static int _a_52_3[] = {11, 0, 15};
static int _a_52_4[] = {18, 0, 16};
static int _a_52_5[] = {33, 0, 17};
static int _a_52_6[] = {36, 0, 18};
static int _a_52_7[] = {37, 0, 19};
static int _a_53_1[] = {-1, 3, 52};
static int _a_53_2[] = {9, 0, 14};
static int _a_53_3[] = {11, 0, 15};
static int _a_53_4[] = {18, 0, 16};
static int _a_53_5[] = {33, 0, 17};
static int _a_53_6[] = {36, 0, 18};
static int _a_53_7[] = {37, 0, 19};
static int _a_54_1[] = {-1, 3, 53};
static int _a_54_2[] = {9, 0, 14};
static int _a_54_3[] = {11, 0, 15};
static int _a_54_4[] = {18, 0, 16};
static int _a_54_5[] = {33, 0, 17};
static int _a_54_6[] = {36, 0, 18};
static int _a_54_7[] = {37, 0, 19};
static int _a_55_1[] = {-1, 3, 54};
static int _a_55_2[] = {9, 0, 14};
static int _a_55_3[] = {11, 0, 15};
static int _a_55_4[] = {18, 0, 16};
static int _a_55_5[] = {33, 0, 17};
static int _a_55_6[] = {36, 0, 18};
static int _a_55_7[] = {37, 0, 19};
static int _a_56_1[] = {-1, 3, 55};
static int _a_56_2[] = {9, 0, 14};
static int _a_56_3[] = {11, 0, 15};
static int _a_56_4[] = {18, 0, 16};
static int _a_56_5[] = {33, 0, 17};
static int _a_56_6[] = {36, 0, 18};
static int _a_56_7[] = {37, 0, 19};
static int _a_57_1[] = {-1, 3, 56};
static int _a_57_2[] = {9, 0, 14};
static int _a_57_3[] = {11, 0, 15};
static int _a_57_4[] = {18, 0, 16};
static int _a_57_5[] = {33, 0, 17};
static int _a_57_6[] = {36, 0, 18};
static int _a_57_7[] = {37, 0, 19};
static int _a_58_1[] = {-1, 3, 57};
static int _a_58_2[] = {9, 0, 14};
static int _a_58_3[] = {11, 0, 15};
static int _a_58_4[] = {18, 0, 16};
static int _a_58_5[] = {33, 0, 17};
static int _a_58_6[] = {36, 0, 18};
static int _a_58_7[] = {37, 0, 19};
static int _a_59_1[] = {-1, 3, 58};
static int _a_59_2[] = {9, 0, 14};
static int _a_59_3[] = {11, 0, 15};
static int _a_59_4[] = {18, 0, 16};
static int _a_59_5[] = {33, 0, 17};
static int _a_59_6[] = {36, 0, 18};
static int _a_59_7[] = {37, 0, 19};
static int _a_60_1[] = {-1, 3, 59};
static int _a_60_2[] = {9, 0, 14};
static int _a_60_3[] = {11, 0, 15};
static int _a_60_4[] = {18, 0, 16};
static int _a_60_5[] = {33, 0, 17};
static int _a_60_6[] = {36, 0, 18};
static int _a_60_7[] = {37, 0, 19};
static int _a_61_1[] = {-1, 3, 60};
static int _a_61_2[] = {9, 0, 14};
static int _a_61_3[] = {11, 0, 15};
static int _a_61_4[] = {18, 0, 16};
static int _a_61_5[] = {33, 0, 17};
static int _a_61_6[] = {36, 0, 18};
static int _a_61_7[] = {37, 0, 19};
static int _a_62_1[] = {-1, 1, 17};
static int _a_63_1[] = {-1, 1, 21};
static int _a_63_2[] = {9, 0, 14};
static int _a_63_3[] = {11, 0, 15};
static int _a_63_4[] = {18, 0, 16};
static int _a_63_5[] = {33, 0, 17};
static int _a_63_6[] = {36, 0, 18};
static int _a_63_7[] = {37, 0, 19};
static int _a_64_1[] = {-1, 1, 15};
static int _a_65_1[] = {-1, 1, 24};
static int _a_66_1[] = {-1, 1, 19};
static int _a_67_1[] = {-1, 3, 66};
static int _a_67_2[] = {32, 0, 91};
static int _a_68_1[] = {-1, 1, 18};
static int _a_69_1[] = {-1, 1, 16};
static int _a_70_1[] = {-1, 1, 20};
static int _a_71_1[] = {-1, 3, 70};
static int _a_71_2[] = {0, 0, 28};
static int _a_71_3[] = {1, 0, 92};
static int _a_71_4[] = {2, 0, 29};
static int _a_71_5[] = {3, 0, 93};
static int _a_71_6[] = {4, 0, 30};
static int _a_71_7[] = {5, 0, 31};
static int _a_71_8[] = {6, 0, 32};
static int _a_71_9[] = {10, 0, 33};
static int _a_71_10[] = {12, 0, 34};
static int _a_71_11[] = {13, 0, 35};
static int _a_71_12[] = {14, 0, 36};
static int _a_71_13[] = {15, 0, 37};
static int _a_71_14[] = {16, 0, 38};
static int _a_71_15[] = {17, 0, 39};
static int _a_72_1[] = {-1, 1, 61};
static int _a_73_1[] = {-1, 1, 11};
static int _a_73_2[] = {0, 0, 28};
static int _a_73_3[] = {2, 0, 29};
static int _a_73_4[] = {4, 0, 30};
static int _a_73_5[] = {5, 0, 31};
static int _a_73_6[] = {6, 0, 32};
static int _a_73_7[] = {10, 0, 33};
static int _a_73_8[] = {12, 0, 34};
static int _a_73_9[] = {13, 0, 35};
static int _a_73_10[] = {14, 0, 36};
static int _a_73_11[] = {15, 0, 37};
static int _a_73_12[] = {16, 0, 38};
static int _a_73_13[] = {17, 0, 39};
static int _a_74_1[] = {-1, 1, 63};
static int _a_75_1[] = {-1, 3, 74};
static int _a_75_2[] = {19, 0, 95};
static int _a_76_1[] = {-1, 1, 53};
static int _a_77_1[] = {-1, 1, 34};
static int _a_77_2[] = {30, 0, 50};
static int _a_78_1[] = {-1, 3, 77};
static int _a_78_2[] = {35, 0, 96};
static int _a_79_1[] = {-1, 1, 36};
static int _a_80_1[] = {-1, 1, 45};
static int _a_80_2[] = {22, 0, 59};
static int _a_80_3[] = {23, 0, 60};
static int _a_81_1[] = {-1, 1, 46};
static int _a_81_2[] = {22, 0, 59};
static int _a_81_3[] = {23, 0, 60};
static int _a_82_1[] = {-1, 1, 38};
static int _a_82_2[] = {20, 0, 51};
static int _a_82_3[] = {21, 0, 52};
static int _a_83_1[] = {-1, 1, 39};
static int _a_83_2[] = {20, 0, 51};
static int _a_83_3[] = {21, 0, 52};
static int _a_84_1[] = {-1, 1, 40};
static int _a_84_2[] = {20, 0, 51};
static int _a_84_3[] = {21, 0, 52};
static int _a_85_1[] = {-1, 1, 41};
static int _a_85_2[] = {20, 0, 51};
static int _a_85_3[] = {21, 0, 52};
static int _a_86_1[] = {-1, 1, 42};
static int _a_86_2[] = {20, 0, 51};
static int _a_86_3[] = {21, 0, 52};
static int _a_87_1[] = {-1, 1, 43};
static int _a_87_2[] = {20, 0, 51};
static int _a_87_3[] = {21, 0, 52};
static int _a_88_1[] = {-1, 1, 48};
static int _a_89_1[] = {-1, 1, 49};
static int _a_90_1[] = {-1, 1, 64};
static int _a_91_1[] = {-1, 1, 22};
static int _a_91_2[] = {9, 0, 14};
static int _a_91_3[] = {11, 0, 15};
static int _a_91_4[] = {18, 0, 16};
static int _a_91_5[] = {33, 0, 17};
static int _a_91_6[] = {36, 0, 18};
static int _a_91_7[] = {37, 0, 19};
static int _a_92_1[] = {-1, 3, 91};
static int _a_92_2[] = {9, 0, 14};
static int _a_92_3[] = {11, 0, 15};
static int _a_92_4[] = {18, 0, 16};
static int _a_92_5[] = {33, 0, 17};
static int _a_92_6[] = {36, 0, 18};
static int _a_92_7[] = {37, 0, 19};
static int _a_93_1[] = {-1, 1, 25};
static int _a_94_1[] = {-1, 3, 93};
static int _a_94_2[] = {0, 0, 28};
static int _a_94_3[] = {1, 0, 99};
static int _a_94_4[] = {2, 0, 29};
static int _a_94_5[] = {4, 0, 30};
static int _a_94_6[] = {5, 0, 31};
static int _a_94_7[] = {6, 0, 32};
static int _a_94_8[] = {10, 0, 33};
static int _a_94_9[] = {12, 0, 34};
static int _a_94_10[] = {13, 0, 35};
static int _a_94_11[] = {14, 0, 36};
static int _a_94_12[] = {15, 0, 37};
static int _a_94_13[] = {16, 0, 38};
static int _a_94_14[] = {17, 0, 39};
static int _a_95_1[] = {-1, 3, 94};
static int _a_95_2[] = {0, 0, 28};
static int _a_95_3[] = {1, 0, 101};
static int _a_95_4[] = {2, 0, 29};
static int _a_95_5[] = {3, 0, 102};
static int _a_95_6[] = {4, 0, 30};
static int _a_95_7[] = {5, 0, 31};
static int _a_95_8[] = {6, 0, 32};
static int _a_95_9[] = {10, 0, 33};
static int _a_95_10[] = {12, 0, 34};
static int _a_95_11[] = {13, 0, 35};
static int _a_95_12[] = {14, 0, 36};
static int _a_95_13[] = {15, 0, 37};
static int _a_95_14[] = {16, 0, 38};
static int _a_95_15[] = {17, 0, 39};
static int _a_96_1[] = {-1, 1, 54};
static int _a_97_1[] = {-1, 3, 96};
static int _a_97_2[] = {9, 0, 14};
static int _a_97_3[] = {11, 0, 15};
static int _a_97_4[] = {18, 0, 16};
static int _a_97_5[] = {33, 0, 17};
static int _a_97_6[] = {36, 0, 18};
static int _a_97_7[] = {37, 0, 19};
static int _a_98_1[] = {-1, 1, 65};
static int _a_99_1[] = {-1, 1, 23};
static int _a_100_1[] = {-1, 1, 27};
static int _a_101_1[] = {-1, 3, 100};
static int _a_101_2[] = {0, 0, 28};
static int _a_101_3[] = {1, 0, 104};
static int _a_101_4[] = {2, 0, 29};
static int _a_101_5[] = {4, 0, 30};
static int _a_101_6[] = {5, 0, 31};
static int _a_101_7[] = {6, 0, 32};
static int _a_101_8[] = {10, 0, 33};
static int _a_101_9[] = {12, 0, 34};
static int _a_101_10[] = {13, 0, 35};
static int _a_101_11[] = {14, 0, 36};
static int _a_101_12[] = {15, 0, 37};
static int _a_101_13[] = {16, 0, 38};
static int _a_101_14[] = {17, 0, 39};
static int _a_102_1[] = {-1, 1, 26};
static int _a_103_1[] = {-1, 3, 102};
static int _a_103_2[] = {0, 0, 28};
static int _a_103_3[] = {1, 0, 105};
static int _a_103_4[] = {2, 0, 29};
static int _a_103_5[] = {4, 0, 30};
static int _a_103_6[] = {5, 0, 31};
static int _a_103_7[] = {6, 0, 32};
static int _a_103_8[] = {10, 0, 33};
static int _a_103_9[] = {12, 0, 34};
static int _a_103_10[] = {13, 0, 35};
static int _a_103_11[] = {14, 0, 36};
static int _a_103_12[] = {15, 0, 37};
static int _a_103_13[] = {16, 0, 38};
static int _a_103_14[] = {17, 0, 39};
static int _a_104_1[] = {-1, 1, 32};
static int _a_105_1[] = {-1, 1, 29};
static int _a_106_1[] = {-1, 1, 28};
static int _a_107_1[] = {-1, 3, 106};
static int _a_107_2[] = {0, 0, 28};
static int _a_107_3[] = {1, 0, 107};
static int _a_107_4[] = {2, 0, 29};
static int _a_107_5[] = {4, 0, 30};
static int _a_107_6[] = {5, 0, 31};
static int _a_107_7[] = {6, 0, 32};
static int _a_107_8[] = {10, 0, 33};
static int _a_107_9[] = {12, 0, 34};
static int _a_107_10[] = {13, 0, 35};
static int _a_107_11[] = {14, 0, 36};
static int _a_107_12[] = {15, 0, 37};
static int _a_107_13[] = {16, 0, 38};
static int _a_107_14[] = {17, 0, 39};
static int _a_108_1[] = {-1, 1, 30};

static int *_a_1[] = {
        (int *)3,
        _a_1_1,
        _a_1_2,
        _a_1_3,
};
static int *_a_2[] = {
        (int *)3,
        _a_2_1,
        _a_2_2,
        _a_2_3,
};
static int *_a_3[] = {
        (int *)2,
        _a_3_1,
        _a_3_2,
};
static int *_a_4[] = {
        (int *)2,
        _a_4_1,
        _a_4_2,
};
static int *_a_5[] = {
        (int *)2,
        _a_5_1,
        _a_5_2,
};
static int *_a_6[] = {
        (int *)1,
        _a_6_1,
};
static int *_a_7[] = {
        (int *)2,
        _a_7_1,
        _a_7_2,
};
static int *_a_8[] = {
        (int *)7,
        _a_8_1,
        _a_8_2,
        _a_8_3,
        _a_8_4,
        _a_8_5,
        _a_8_6,
        _a_8_7,
};
static int *_a_9[] = {
        (int *)1,
        _a_9_1,
};
static int *_a_10[] = {
        (int *)1,
        _a_10_1,
};
static int *_a_11[] = {
        (int *)3,
        _a_11_1,
        _a_11_2,
        _a_11_3,
};
static int *_a_12[] = {
        (int *)14,
        _a_12_1,
        _a_12_2,
        _a_12_3,
        _a_12_4,
        _a_12_5,
        _a_12_6,
        _a_12_7,
        _a_12_8,
        _a_12_9,
        _a_12_10,
        _a_12_11,
        _a_12_12,
        _a_12_13,
        _a_12_14,
};
static int *_a_13[] = {
        (int *)2,
        _a_13_1,
        _a_13_2,
};
static int *_a_14[] = {
        (int *)1,
        _a_14_1,
};
static int *_a_15[] = {
        (int *)1,
        _a_15_1,
};
static int *_a_16[] = {
        (int *)2,
        _a_16_1,
        _a_16_2,
};
static int *_a_17[] = {
        (int *)7,
        _a_17_1,
        _a_17_2,
        _a_17_3,
        _a_17_4,
        _a_17_5,
        _a_17_6,
        _a_17_7,
};
static int *_a_18[] = {
        (int *)7,
        _a_18_1,
        _a_18_2,
        _a_18_3,
        _a_18_4,
        _a_18_5,
        _a_18_6,
        _a_18_7,
};
static int *_a_19[] = {
        (int *)1,
        _a_19_1,
};
static int *_a_20[] = {
        (int *)1,
        _a_20_1,
};
static int *_a_21[] = {
        (int *)1,
        _a_21_1,
};
static int *_a_22[] = {
        (int *)3,
        _a_22_1,
        _a_22_2,
        _a_22_3,
};
static int *_a_23[] = {
        (int *)2,
        _a_23_1,
        _a_23_2,
};
static int *_a_24[] = {
        (int *)1,
        _a_24_1,
};
static int *_a_25[] = {
        (int *)9,
        _a_25_1,
        _a_25_2,
        _a_25_3,
        _a_25_4,
        _a_25_5,
        _a_25_6,
        _a_25_7,
        _a_25_8,
        _a_25_9,
};
static int *_a_26[] = {
        (int *)3,
        _a_26_1,
        _a_26_2,
        _a_26_3,
};
static int *_a_27[] = {
        (int *)1,
        _a_27_1,
};
static int *_a_28[] = {
        (int *)1,
        _a_28_1,
};
static int *_a_29[] = {
        (int *)1,
        _a_29_1,
};
static int *_a_30[] = {
        (int *)1,
        _a_30_1,
};
static int *_a_31[] = {
        (int *)7,
        _a_31_1,
        _a_31_2,
        _a_31_3,
        _a_31_4,
        _a_31_5,
        _a_31_6,
        _a_31_7,
};
static int *_a_32[] = {
        (int *)2,
        _a_32_1,
        _a_32_2,
};
static int *_a_33[] = {
        (int *)7,
        _a_33_1,
        _a_33_2,
        _a_33_3,
        _a_33_4,
        _a_33_5,
        _a_33_6,
        _a_33_7,
};
static int *_a_34[] = {
        (int *)7,
        _a_34_1,
        _a_34_2,
        _a_34_3,
        _a_34_4,
        _a_34_5,
        _a_34_6,
        _a_34_7,
};
static int *_a_35[] = {
        (int *)7,
        _a_35_1,
        _a_35_2,
        _a_35_3,
        _a_35_4,
        _a_35_5,
        _a_35_6,
        _a_35_7,
};
static int *_a_36[] = {
        (int *)2,
        _a_36_1,
        _a_36_2,
};
static int *_a_37[] = {
        (int *)7,
        _a_37_1,
        _a_37_2,
        _a_37_3,
        _a_37_4,
        _a_37_5,
        _a_37_6,
        _a_37_7,
};
static int *_a_38[] = {
        (int *)7,
        _a_38_1,
        _a_38_2,
        _a_38_3,
        _a_38_4,
        _a_38_5,
        _a_38_6,
        _a_38_7,
};
static int *_a_39[] = {
        (int *)7,
        _a_39_1,
        _a_39_2,
        _a_39_3,
        _a_39_4,
        _a_39_5,
        _a_39_6,
        _a_39_7,
};
static int *_a_40[] = {
        (int *)7,
        _a_40_1,
        _a_40_2,
        _a_40_3,
        _a_40_4,
        _a_40_5,
        _a_40_6,
        _a_40_7,
};
static int *_a_41[] = {
        (int *)1,
        _a_41_1,
};
static int *_a_42[] = {
        (int *)1,
        _a_42_1,
};
static int *_a_43[] = {
        (int *)1,
        _a_43_1,
};
static int *_a_44[] = {
        (int *)14,
        _a_44_1,
        _a_44_2,
        _a_44_3,
        _a_44_4,
        _a_44_5,
        _a_44_6,
        _a_44_7,
        _a_44_8,
        _a_44_9,
        _a_44_10,
        _a_44_11,
        _a_44_12,
        _a_44_13,
        _a_44_14,
};
static int *_a_45[] = {
        (int *)13,
        _a_45_1,
        _a_45_2,
        _a_45_3,
        _a_45_4,
        _a_45_5,
        _a_45_6,
        _a_45_7,
        _a_45_8,
        _a_45_9,
        _a_45_10,
        _a_45_11,
        _a_45_12,
        _a_45_13,
};
static int *_a_46[] = {
        (int *)7,
        _a_46_1,
        _a_46_2,
        _a_46_3,
        _a_46_4,
        _a_46_5,
        _a_46_6,
        _a_46_7,
};
static int *_a_47[] = {
        (int *)2,
        _a_47_1,
        _a_47_2,
};
static int *_a_48[] = {
        (int *)1,
        _a_48_1,
};
static int *_a_49[] = {
        (int *)7,
        _a_49_1,
        _a_49_2,
        _a_49_3,
        _a_49_4,
        _a_49_5,
        _a_49_6,
        _a_49_7,
};
static int *_a_50[] = {
        (int *)7,
        _a_50_1,
        _a_50_2,
        _a_50_3,
        _a_50_4,
        _a_50_5,
        _a_50_6,
        _a_50_7,
};
static int *_a_51[] = {
        (int *)7,
        _a_51_1,
        _a_51_2,
        _a_51_3,
        _a_51_4,
        _a_51_5,
        _a_51_6,
        _a_51_7,
};
static int *_a_52[] = {
        (int *)7,
        _a_52_1,
        _a_52_2,
        _a_52_3,
        _a_52_4,
        _a_52_5,
        _a_52_6,
        _a_52_7,
};
static int *_a_53[] = {
        (int *)7,
        _a_53_1,
        _a_53_2,
        _a_53_3,
        _a_53_4,
        _a_53_5,
        _a_53_6,
        _a_53_7,
};
static int *_a_54[] = {
        (int *)7,
        _a_54_1,
        _a_54_2,
        _a_54_3,
        _a_54_4,
        _a_54_5,
        _a_54_6,
        _a_54_7,
};
static int *_a_55[] = {
        (int *)7,
        _a_55_1,
        _a_55_2,
        _a_55_3,
        _a_55_4,
        _a_55_5,
        _a_55_6,
        _a_55_7,
};
static int *_a_56[] = {
        (int *)7,
        _a_56_1,
        _a_56_2,
        _a_56_3,
        _a_56_4,
        _a_56_5,
        _a_56_6,
        _a_56_7,
};
static int *_a_57[] = {
        (int *)7,
        _a_57_1,
        _a_57_2,
        _a_57_3,
        _a_57_4,
        _a_57_5,
        _a_57_6,
        _a_57_7,
};
static int *_a_58[] = {
        (int *)7,
        _a_58_1,
        _a_58_2,
        _a_58_3,
        _a_58_4,
        _a_58_5,
        _a_58_6,
        _a_58_7,
};
static int *_a_59[] = {
        (int *)7,
        _a_59_1,
        _a_59_2,
        _a_59_3,
        _a_59_4,
        _a_59_5,
        _a_59_6,
        _a_59_7,
};
static int *_a_60[] = {
        (int *)7,
        _a_60_1,
        _a_60_2,
        _a_60_3,
        _a_60_4,
        _a_60_5,
        _a_60_6,
        _a_60_7,
};
static int *_a_61[] = {
        (int *)7,
        _a_61_1,
        _a_61_2,
        _a_61_3,
        _a_61_4,
        _a_61_5,
        _a_61_6,
        _a_61_7,
};
static int *_a_62[] = {
        (int *)1,
        _a_62_1,
};
static int *_a_63[] = {
        (int *)7,
        _a_63_1,
        _a_63_2,
        _a_63_3,
        _a_63_4,
        _a_63_5,
        _a_63_6,
        _a_63_7,
};
static int *_a_64[] = {
        (int *)1,
        _a_64_1,
};
static int *_a_65[] = {
        (int *)1,
        _a_65_1,
};
static int *_a_66[] = {
        (int *)1,
        _a_66_1,
};
static int *_a_67[] = {
        (int *)2,
        _a_67_1,
        _a_67_2,
};
static int *_a_68[] = {
        (int *)1,
        _a_68_1,
};
static int *_a_69[] = {
        (int *)1,
        _a_69_1,
};
static int *_a_70[] = {
        (int *)1,
        _a_70_1,
};
static int *_a_71[] = {
        (int *)15,
        _a_71_1,
        _a_71_2,
        _a_71_3,
        _a_71_4,
        _a_71_5,
        _a_71_6,
        _a_71_7,
        _a_71_8,
        _a_71_9,
        _a_71_10,
        _a_71_11,
        _a_71_12,
        _a_71_13,
        _a_71_14,
        _a_71_15,
};
static int *_a_72[] = {
        (int *)1,
        _a_72_1,
};
static int *_a_73[] = {
        (int *)13,
        _a_73_1,
        _a_73_2,
        _a_73_3,
        _a_73_4,
        _a_73_5,
        _a_73_6,
        _a_73_7,
        _a_73_8,
        _a_73_9,
        _a_73_10,
        _a_73_11,
        _a_73_12,
        _a_73_13,
};
static int *_a_74[] = {
        (int *)1,
        _a_74_1,
};
static int *_a_75[] = {
        (int *)2,
        _a_75_1,
        _a_75_2,
};
static int *_a_76[] = {
        (int *)1,
        _a_76_1,
};
static int *_a_77[] = {
        (int *)2,
        _a_77_1,
        _a_77_2,
};
static int *_a_78[] = {
        (int *)2,
        _a_78_1,
        _a_78_2,
};
static int *_a_79[] = {
        (int *)1,
        _a_79_1,
};
static int *_a_80[] = {
        (int *)3,
        _a_80_1,
        _a_80_2,
        _a_80_3,
};
static int *_a_81[] = {
        (int *)3,
        _a_81_1,
        _a_81_2,
        _a_81_3,
};
static int *_a_82[] = {
        (int *)3,
        _a_82_1,
        _a_82_2,
        _a_82_3,
};
static int *_a_83[] = {
        (int *)3,
        _a_83_1,
        _a_83_2,
        _a_83_3,
};
static int *_a_84[] = {
        (int *)3,
        _a_84_1,
        _a_84_2,
        _a_84_3,
};
static int *_a_85[] = {
        (int *)3,
        _a_85_1,
        _a_85_2,
        _a_85_3,
};
static int *_a_86[] = {
        (int *)3,
        _a_86_1,
        _a_86_2,
        _a_86_3,
};
static int *_a_87[] = {
        (int *)3,
        _a_87_1,
        _a_87_2,
        _a_87_3,
};
static int *_a_88[] = {
        (int *)1,
        _a_88_1,
};
static int *_a_89[] = {
        (int *)1,
        _a_89_1,
};
static int *_a_90[] = {
        (int *)1,
        _a_90_1,
};
static int *_a_91[] = {
        (int *)7,
        _a_91_1,
        _a_91_2,
        _a_91_3,
        _a_91_4,
        _a_91_5,
        _a_91_6,
        _a_91_7,
};
static int *_a_92[] = {
        (int *)7,
        _a_92_1,
        _a_92_2,
        _a_92_3,
        _a_92_4,
        _a_92_5,
        _a_92_6,
        _a_92_7,
};
static int *_a_93[] = {
        (int *)1,
        _a_93_1,
};
static int *_a_94[] = {
        (int *)14,
        _a_94_1,
        _a_94_2,
        _a_94_3,
        _a_94_4,
        _a_94_5,
        _a_94_6,
        _a_94_7,
        _a_94_8,
        _a_94_9,
        _a_94_10,
        _a_94_11,
        _a_94_12,
        _a_94_13,
        _a_94_14,
};
static int *_a_95[] = {
        (int *)15,
        _a_95_1,
        _a_95_2,
        _a_95_3,
        _a_95_4,
        _a_95_5,
        _a_95_6,
        _a_95_7,
        _a_95_8,
        _a_95_9,
        _a_95_10,
        _a_95_11,
        _a_95_12,
        _a_95_13,
        _a_95_14,
        _a_95_15,
};
static int *_a_96[] = {
        (int *)1,
        _a_96_1,
};
static int *_a_97[] = {
        (int *)7,
        _a_97_1,
        _a_97_2,
        _a_97_3,
        _a_97_4,
        _a_97_5,
        _a_97_6,
        _a_97_7,
};
static int *_a_98[] = {
        (int *)1,
        _a_98_1,
};
static int *_a_99[] = {
        (int *)1,
        _a_99_1,
};
static int *_a_100[] = {
        (int *)1,
        _a_100_1,
};
static int *_a_101[] = {
        (int *)14,
        _a_101_1,
        _a_101_2,
        _a_101_3,
        _a_101_4,
        _a_101_5,
        _a_101_6,
        _a_101_7,
        _a_101_8,
        _a_101_9,
        _a_101_10,
        _a_101_11,
        _a_101_12,
        _a_101_13,
        _a_101_14,
};
static int *_a_102[] = {
        (int *)1,
        _a_102_1,
};
static int *_a_103[] = {
        (int *)14,
        _a_103_1,
        _a_103_2,
        _a_103_3,
        _a_103_4,
        _a_103_5,
        _a_103_6,
        _a_103_7,
        _a_103_8,
        _a_103_9,
        _a_103_10,
        _a_103_11,
        _a_103_12,
        _a_103_13,
        _a_103_14,
};
static int *_a_104[] = {
        (int *)1,
        _a_104_1,
};
static int *_a_105[] = {
        (int *)1,
        _a_105_1,
};
static int *_a_106[] = {
        (int *)1,
        _a_106_1,
};
static int *_a_107[] = {
        (int *)14,
        _a_107_1,
        _a_107_2,
        _a_107_3,
        _a_107_4,
        _a_107_5,
        _a_107_6,
        _a_107_7,
        _a_107_8,
        _a_107_9,
        _a_107_10,
        _a_107_11,
        _a_107_12,
        _a_107_13,
        _a_107_14,
};
static int *_a_108[] = {
        (int *)1,
        _a_108_1,
};

static int **action_table[] = {
        _a_1,
        _a_2,
        _a_3,
        _a_4,
        _a_5,
        _a_6,
        _a_7,
        _a_8,
        _a_9,
        _a_10,
        _a_11,
        _a_12,
        _a_13,
        _a_14,
        _a_15,
        _a_16,
        _a_17,
        _a_18,
        _a_19,
        _a_20,
        _a_21,
        _a_22,
        _a_23,
        _a_24,
        _a_25,
        _a_26,
        _a_27,
        _a_28,
        _a_29,
        _a_30,
        _a_31,
        _a_32,
        _a_33,
        _a_34,
        _a_35,
        _a_36,
        _a_37,
        _a_38,
        _a_39,
        _a_40,
        _a_41,
        _a_42,
        _a_43,
        _a_44,
        _a_45,
        _a_46,
        _a_47,
        _a_48,
        _a_49,
        _a_50,
        _a_51,
        _a_52,
        _a_53,
        _a_54,
        _a_55,
        _a_56,
        _a_57,
        _a_58,
        _a_59,
        _a_60,
        _a_61,
        _a_62,
        _a_63,
        _a_64,
        _a_65,
        _a_66,
        _a_67,
        _a_68,
        _a_69,
        _a_70,
        _a_71,
        _a_72,
        _a_73,
        _a_74,
        _a_75,
        _a_76,
        _a_77,
        _a_78,
        _a_79,
        _a_80,
        _a_81,
        _a_82,
        _a_83,
        _a_84,
        _a_85,
        _a_86,
        _a_87,
        _a_88,
        _a_89,
        _a_90,
        _a_91,
        _a_92,
        _a_93,
        _a_94,
        _a_95,
        _a_96,
        _a_97,
        _a_98,
        _a_99,
        _a_100,
        _a_101,
        _a_102,
        _a_103,
        _a_104,
        _a_105,
        _a_106,
        _a_107,
        _a_108,
};
};

namespace {
class Stack {
public:
  typedef std::vector<std::list<Node> > elems_t;

private:
  struct State {
    int state;
    elems_t elems;
  };

  typedef std::list<State> stack_t;

public:
  inline Stack ()
  {
    list.push_back (State());
    it = list.begin();
  }

  elems_t& push (int state);
  elems_t& pop();

  inline int state ()
  {
    return (*it).state;
  }

private:
  stack_t list;
  stack_t::iterator it;
};

Stack::elems_t& Stack::push (int state)
{
  it++;
  if ( it == list.end() ) { list.push_back (State()); it = list.end(); it--; }

  State &s = *it;
  s.state = state;
  s.elems.clear();
  return s.elems;
}

Stack::elems_t& Stack::pop()
{
  State&s = *it;
  it--;
  return s.elems;
}

int errors[] = {
0, 1, 2, 3, 4, 4, 4, 5, 1, 1, 1, 6, 4, 4, 7, 8, 5, 5, 7, 7, 1, 9, 10, 10, 11, 7, 7, 1, 12, 12, 5, 2, 5, 5, 5, 2, 5, 5, 5, 5, 6, 6, 12, 6, 13, 5, 14, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 12, 15, 12, 12, 12, 16, 12, 12, 12, 17, 6, 13, 12, 14, 7, 10, 18, 10, 7, 7, 19, 19, 19, 19, 19, 19, 7, 7, 15, 15, 5, 12, 20, 17, 7, 5, 15, 12, 12, 20, 12, 20, 21, 12, 12, 20, 12, 
};

char * error_messages[] = {
        "expecting: 'plan', 'proc', EOF",
        "expecting: 'proc', 'wait', color, EOF",
        "expecting: identifier",
        "expecting: EOF",
        "expecting: 'proc', EOF",
        "expecting: 'rand', 'sine', '(', '~', number, identifier",
        "expecting: 'defy', 'draw', 'face', 'fork', 'move', 'proc', 'seed', 'size', 'temp', 'tint', 'turn', 'wait', 'when', identifier, EOF",
        "expecting: 'defy', 'done', 'draw', 'else', 'face', 'fork', 'move', 'proc', 'rand', 'seed', 'sine', 'size', 'temp', 'tint', 'turn', 'wait', 'when', '(', ')', '+', '-', '*', '/', '--', '!=', '<', '<=', '>', '>=', '&', '|', '~', '?', ':', number, identifier, color, EOF",
        "expecting: '('",
        "expecting: 'defy', 'done', 'draw', 'else', 'face', 'fork', 'move', 'proc', 'rand', 'seed', 'sine', 'size', 'temp', 'tint', 'turn', 'wait', 'when', '(', ')', '|', '~', '?', ':', number, identifier, color, EOF",
        "expecting: 'defy', 'done', 'draw', 'else', 'face', 'fork', 'move', 'proc', 'rand', 'seed', 'sine', 'size', 'temp', 'tint', 'turn', 'wait', 'when', '(', ')', '&', '|', '~', '?', ':', number, identifier, color, EOF",
        "expecting: 'defy', 'done', 'draw', 'else', 'face', 'fork', 'move', 'proc', 'rand', 'seed', 'sine', 'size', 'temp', 'tint', 'turn', 'wait', 'when', '(', ')', '+', '-', '--', '!=', '<', '<=', '>', '>=', '&', '|', '~', '?', ':', number, identifier, color, EOF",
        "expecting: 'defy', 'done', 'draw', 'else', 'face', 'fork', 'move', 'proc', 'seed', 'size', 'temp', 'tint', 'turn', 'wait', 'when', EOF",
        "expecting: 'defy', 'draw', 'face', 'fork', 'move', 'proc', 'seed', 'size', 'temp', 'tint', 'turn', 'wait', 'when', EOF",
        "expecting: ')'",
        "expecting: 'defy', 'done', 'draw', 'else', 'face', 'fork', 'move', 'proc', 'rand', 'seed', 'sine', 'size', 'temp', 'tint', 'turn', 'wait', 'when', '(', '~', number, identifier, EOF",
        "expecting: '='",
        "expecting: 'defy', 'done', 'draw', 'else', 'face', 'fork', 'move', 'seed', 'size', 'temp', 'tint', 'turn', 'wait', 'when'",
        "expecting: ':'",
        "expecting: 'defy', 'done', 'draw', 'else', 'face', 'fork', 'move', 'proc', 'rand', 'seed', 'sine', 'size', 'temp', 'tint', 'turn', 'wait', 'when', '(', ')', '+', '-', '&', '|', '~', '?', ':', number, identifier, color, EOF",
        "expecting: 'defy', 'done', 'draw', 'face', 'fork', 'move', 'seed', 'size', 'temp', 'tint', 'turn', 'wait', 'when'",
        "expecting: 'defy', 'done', 'draw', 'else', 'face', 'fork', 'move', 'proc', 'rand', 'seed', 'sine', 'size', 'temp', 'tint', 'turn', 'wait', 'when', '(', ')', '~', ':', number, identifier, color, EOF",
};

int goTo(int index, int state)
{
  int low = 2;
  int high = (int) reinterpret_cast<size_t>(goto_table[index][0]);
  int value = goto_table[index][1][1];

  while(low <= high) {
      int middle = (low + high) / 2;

      if(state < goto_table[index][middle][0]) {
          high = middle - 1;
      } else if(state > goto_table[index][middle][0]) {
          low = middle + 1;
      } else {
          value = goto_table[index][middle][1];
          break;
      }
  }

  return value;
}

} // namespace {


rose::Parser::Parser (Lexer *lexer, bool own_lexer) : lexer (lexer), own_lexer (own_lexer)
{
}

rose::Parser::~Parser ()
{
  if ( own_lexer ) delete lexer;
}

rose::Start rose::Parser::parse ()
{
  Node null_node;

  Stack stack;
  stack.push (0);

  while (true) {
      while ( lexer->peek().getIndex() == -1 )
          lexer->next();

      Token last_token = lexer->peek();
      int last_pos = last_token.getPos();
      int last_line = last_token.getLine();

      int state = stack.state();

      int index = last_token.getIndex();
      int action[2] = { action_table[state][1][1], action_table[state][1][2] };

      int low = 2;
      int high = (int) reinterpret_cast<size_t>(action_table[state][0]);

      while(low <= high) {
          int middle = (low + high) / 2;

          if(index < action_table[state][middle][0]) {
              high = middle - 1;
          } else if ( index > action_table[state][middle][0] ) {
              low = middle + 1;
          } else {
              action[0] = action_table[state][middle][1];
              action[1] = action_table[state][middle][2];
              break;
          }
      }

      switch(action[0]) {
        case SHIFT: {
          Stack::elems_t& elems = stack.push(action[1]);
          std::list<Node> l;
          l.push_back (lexer->next());
          elems.push_back (l);
          break;
        }

        case ACCEPT: {
          TEOF node2 = lexer->next().unsafe_cast<TEOF>();
          Stack::elems_t& top = stack.pop();
          PProgram node1 = top.front().front().unsafe_cast<PProgram>();
          Start node = Start::make (node1, node2);
          return node;
          break;
        }

        case ERROR: {
          std::ostringstream out;
          out << "[" << last_line << "," << last_pos << "] " << error_messages[errors[action[1]]];
          throw ParserException (last_token, out.str());
          break;
        }

        case REDUCE: {
          // here comes the significant part
          reduce_command *cmds = reduce_commands[action[1]].commands;
          int cmds_count = reduce_commands[action[1]].count;
          int go_to = reduce_commands[action[1]].go_to;

          std::list<Node> lists[4];
          Node nodes[5];
          Stack::elems_t pops[6];
          void *args[5];

          Stack::elems_t result;

          for ( int cid = 0; cid < cmds_count; cid++ ) {
              reduce_command& cmd = cmds[cid];

              switch (cmd.cmd) {
                case CMD_POP: {
                  pops[cmd.result] = stack.pop();
                  break;
                }
                case CMD_FETCHNODE: {
                  nodes[cmd.result] = pops[cmd.from][cmd.index].front();
                  break;
                }
                case CMD_FETCHLIST: {
                  lists[cmd.result] = pops[cmd.from][cmd.index];
                  break;
                }
                case CMD_ADDNODE: {
                  if ( nodes[cmd.from] )
                      lists[cmd.result].push_back (nodes[cmd.from]);
                  break;
                }
                case CMD_ADDLIST: {
                  lists[cmd.result].insert(lists[cmd.result].end(), lists[cmd.from].begin(), lists[cmd.from].end());
                  break;
                }
                case CMD_MAKELIST: {
                  lists[cmd.result].clear();
                  break;
                }
                case CMD_MAKENODE: {
                  // XXX what?
                  for ( int i = 0; i < cmd.type_info->prod_elem_count; i++ ) {
                      if ( cmd.type_info->prod_elem_is_list[i] ) {
                          args[i] = (void *)&lists[cmd.args[i]];
                      } else {
                          if ( cmd.args[i] == -1 )
                              args[i] = (void *)&null_node;
                          else
                              args[i] = (void *)&nodes[cmd.args[i]];
                      }
                  }
                  nodes[cmd.result] = _GenericNode::initProd (cmd.type_info, args);
                  break;
                }
                case CMD_RETURNNODE: {
                  std::list<Node> l;
                  if ( cmd.from == -1 )
                      l.push_back (null_node);
                  else
                      l.push_back (nodes[cmd.from]);
                  result.push_back(l);
                  break;
                }
                case CMD_RETURNLIST: {
                  result.push_back(lists[cmd.from]);
                  break;
                }
              }
          }

          stack.push(goTo(go_to, stack.state())) = result;

          break;
        }
      }
  }
  throw Exception ("Should never get here");
}
